const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const dbPath = path.resolve(__dirname, '../erp.db');
const db = new sqlite3.Database(dbPath);

console.log('Starting dummy data generation...');

db.serialize(() => {
  // Ensure tables exist
  db.exec(`
    CREATE TABLE IF NOT EXISTS automations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      trigger_event TEXT NOT NULL,
      action_type TEXT NOT NULL,
      action_payload TEXT,
      is_active INTEGER DEFAULT 1,
      created_by INTEGER REFERENCES members(id) ON DELETE SET NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS automation_logs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      automation_id INTEGER REFERENCES automations(id) ON DELETE CASCADE,
      triggered_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      status TEXT DEFAULT 'SUCCESS',
      details TEXT
    );
  `);

  // 1. Generate 50+ diverse Tasks
  const statuses = ['Pending', 'In Progress', 'Done'];
  const titles = [
    'Update quarterly financial report', 'Review Q3 marketing strategy', 'Fix server deployment issue',
    'Onboard new engineering hire', 'Draft new client proposal', 'Organize team building event',
    'Update privacy policy', 'Optimize database queries', 'Prepare slides for all-hands',
    'Audit AWS infrastructure', 'Design new landing page', 'Implement OAuth2 login',
    'Resolve customer ticket #829', 'Plan Q4 roadmap', 'Interview candidate for UI/UX role',
    'Deploy hotfix for iOS app', 'Review legal contracts for vendor', 'Order new office equipment'
  ];

  const stmtTasks = db.prepare(`INSERT INTO tasks (title, description, status, assigned_to, deadline, task_date) VALUES (?, ?, ?, ?, ?, ?)`);
  for (let i = 0; i < 50; i++) {
    const title = titles[Math.floor(Math.random() * titles.length)] + ` (Batch ${i})`;
    const status = statuses[Math.floor(Math.random() * statuses.length)];
    const memberId = Math.floor(Math.random() * 4) + 2; // Employees ID 2,3,4,5
    
    // Random deadline between 7 days ago and 14 days from now
    const d = new Date();
    d.setDate(d.getDate() + (Math.floor(Math.random() * 21) - 7));
    
    stmtTasks.run(title, 'Autogenerated dummy task description.', status, memberId, d.toISOString(), d.toISOString().split('T')[0]);
  }
  stmtTasks.finalize();

  // 2. Generate 100+ Financial Expenses
  const categories = ['IT & Software', 'Office Supplies', 'Travel', 'Marketing', 'Utilities', 'Miscellaneous'];
  const companies = ['Trade Division', 'Digital Division'];
  
  const stmtExp = db.prepare(`INSERT INTO expenses (description, amount, expense_date, category_id, company_name, expense_head, entered_by) VALUES (?, ?, ?, ?, ?, ?, ?)`);
  for (let i = 0; i < 120; i++) {
    const amount = Math.floor(Math.random() * 5000) + 100;
    const catId = Math.floor(Math.random() * categories.length) + 1; // Assuming IDs 1-6
    const comp = companies[Math.floor(Math.random() * companies.length)];
    
    // Random date within the last 6 months
    const d = new Date();
    d.setMonth(d.getMonth() - Math.floor(Math.random() * 6));
    d.setDate(Math.floor(Math.random() * 28) + 1);

    stmtExp.run(`Expense Record #${i}`, amount, d.toISOString().split('T')[0], catId, comp, 'Operational', 1);
  }
  stmtExp.finalize();

  // 3. Generate Leave Requests
  const stmtLeaves = db.prepare(`INSERT INTO leave_requests (member_id, leave_type, start_date, end_date, reason, status) VALUES (?, ?, ?, ?, ?, ?)`);
  const leaveTypes = ['Sick', 'Annual', 'Casual'];
  for (let i = 0; i < 15; i++) {
    const d1 = new Date();
    d1.setDate(d1.getDate() + Math.floor(Math.random() * 30));
    const d2 = new Date(d1);
    d2.setDate(d2.getDate() + Math.floor(Math.random() * 3) + 1);
    
    stmtLeaves.run(
      Math.floor(Math.random() * 4) + 2, 
      leaveTypes[Math.floor(Math.random() * leaveTypes.length)], 
      d1.toISOString().split('T')[0], 
      d2.toISOString().split('T')[0], 
      'Dummy reason for leave', 
      Math.random() > 0.5 ? 'Approved' : 'Pending'
    );
  }
  stmtLeaves.finalize();

  // 4. Generate Meetings
  const stmtMeetings = db.prepare(`INSERT INTO meetings (title, scheduled_at, contact_name) VALUES (?, ?, ?)`);
  for (let i = 0; i < 10; i++) {
    const d = new Date();
    d.setDate(d.getDate() + Math.floor(Math.random() * 14));
    stmtMeetings.run(
      `Client Sync ${i+1}`, 
      d.toISOString(), 
      Math.random() > 0.5 ? 'Zoom' : 'Conference Room A'
    );
  }
  stmtMeetings.finalize();

  // 5. Generate Tenders
  const stmtTenders = db.prepare(`INSERT INTO tenders (title, organization, submission_deadline, status, estimated_value, documents_url) VALUES (?, ?, ?, ?, ?, ?)`);
  const tStatus = ['UPCOMING', 'SUBMITTED', 'WON', 'LOST'];
  for (let i = 0; i < 15; i++) {
    const d = new Date();
    d.setDate(d.getDate() + (Math.floor(Math.random() * 60) - 20));
    stmtTenders.run(
      `Government Project RFP ${i}`, 
      `Ministry of IT #${i}`, 
      d.toISOString(), 
      tStatus[Math.floor(Math.random() * tStatus.length)], 
      (Math.floor(Math.random() * 100) + 10) * 1000, 
      'https://example.com/docs'
    );
  }
  stmtTenders.finalize();

  // 6. Generate Automations
  const stmtAuto = db.prepare(`INSERT INTO automations (name, trigger_event, action_type, is_active) VALUES (?, ?, ?, ?)`);
  stmtAuto.run('Alert Manager on Tender Won', 'TENDER_WON', 'SEND_EMAIL', 1);
  stmtAuto.run('Welcome Email to New Hire', 'USER_JOINED', 'SEND_EMAIL', 1);
  stmtAuto.run('Log Major Expenses', 'NEW_EXPENSE', 'LOG_EVENT', 1);
  stmtAuto.run('Auto-assign Task to HR on Leave Request', 'LEAVE_REQUESTED', 'CREATE_TASK', 0);
  stmtAuto.finalize();

  console.log('Dummy data generation complete!');
});

db.close();
