/**
 * src/backend.ts
 *
 * Express API server for ERP-connect.
 *
 * Architecture: All API routes are mounted inside a single async factory function
 * `createBackendApp()`. This is called once by `server.ts` which then attaches
 * the Next.js request handler for the frontend. The two apps share a single
 * HTTP port (default 3000, overridden by the PORT env variable).
 *
 * Notification channel: Email only (via Brevo / `src/brevo.ts`).
 *   All Telegram and WhatsApp integrations have been removed.
 *
 * Authentication: JWT-based bearer tokens + HTTP-only cookie fallback.
 *   Tokens are signed with JWT_SECRET (auto-generated by Render or set manually).
 *   Rate-limiting is applied to the login endpoint (10 attempts / 15 min / IP).
 *
 * Database: Dual-mode via `src/db.ts` — SQLite for local dev, PostgreSQL for
 *   production (triggered by the DATABASE_URL environment variable).
 *
 * @module backend
 */

import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { initDB, dbAll, dbGet, dbRun, isPostgres, tenantStorage } from './db.js';
import {
  sendBrevoEmail,
  resolveMemberNotificationEmails,
  schedule24And15HourReminders,
  scheduleTenderReminders,
  scheduleCustomReminders,
  processDueEmailJobs,
  buildAolErpHtml,
} from './brevo.js';

// ─────────────────────────────────────────────────────────────────────────────
// Re-export DB helpers so `server.ts` can use them without importing `db.ts` directly
// ─────────────────────────────────────────────────────────────────────────────
export { initDB, dbAll, dbGet, dbRun, isPostgres };

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

/** JWT secret — always falls back to a built-in default so the app boots even without env vars. */
const JWT_SECRET = process.env.JWT_SECRET || 'erp-connect_super_secret_key_2024!';

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Inserts an in-app notification for a single member.
 * Email notifications are handled separately via Brevo routes.
 */
async function notifyMember(memberId: number, message: string, link = '') {
  await dbRun(
    `INSERT INTO notifications(member_id, message, link) VALUES (?, ?, ?)`,
    [memberId, message, link],
  );
}

/**
 * Inserts an in-app notification for every Admin member.
 */
async function notifyAdmins(message: string, link = '') {
  const admins = await dbAll(`SELECT id FROM members WHERE role = 'Admin'`) as any[];
  for (const admin of admins) {
    await dbRun(
      `INSERT INTO notifications(member_id, message, link) VALUES (?, ?, ?)`,
      [admin.id, message, link],
    );
  }
}

/**
 * Formats reminder offset parts (days / hours / minutes) into a human-readable string,
 * e.g. `"2 day(s), 30 minute(s)"`.
 */
function formatReminderLabel(
  days?: number | null,
  hours?: number | null,
  minutes?: number | null,
): string {
  const parts: string[] = [];
  if (Number(days)    > 0) parts.push(`${Number(days)} day(s)`);
  if (Number(hours)   > 0) parts.push(`${Number(hours)} hour(s)`);
  if (Number(minutes) > 0) parts.push(`${Number(minutes)} minute(s)`);
  return parts.join(', ');
}

/**
 * Creates an in-app notification for Admins when a reminder is configured on an entity.
 * Also notifies the associated member if they are not an Admin.
 */
async function notifyReminderConfigured(params: {
  entityLabel: string;
  title: string;
  link: string;
  remDays?: number | null;
  remHours?: number | null;
  remMins?: number | null;
  alsoMemberId?: number | null;
}) {
  const label = formatReminderLabel(params.remDays, params.remHours, params.remMins);
  if (!label) return;

  const msg = `Reminder set for ${params.entityLabel}: "${params.title}" (${label} before).`;
  await notifyAdmins(msg, params.link);

  if (params.alsoMemberId) {
    const member = await dbGet(`SELECT role FROM members WHERE id = ?`, [params.alsoMemberId]) as any;
    if (member && member.role !== 'Admin') {
      await dbRun(
        `INSERT INTO notifications(member_id, message, link) VALUES (?, ?, ?)`,
        [params.alsoMemberId, msg, params.link],
      );
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Exported utility functions (used by tests / future middleware)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Extracts a clean client IP address from a request, handling reverse-proxy headers
 * (Cloudflare, nginx, Render) and normalising IPv6-mapped IPv4 addresses.
 */
export function getCleanClientIp(req: express.Request): string {
  const forwarded =
    req.headers['x-forwarded-for'] ||
    req.headers['x-real-ip'] ||
    req.headers['cf-connecting-ip'];

  let rawIp = '';
  if (typeof forwarded === 'string') {
    rawIp = (forwarded.split(',')[0] || '').trim();
  } else if (Array.isArray(forwarded) && forwarded.length > 0) {
    rawIp = String(forwarded[0] || '').trim();
  } else {
    rawIp = req.socket?.remoteAddress || '';
  }

  // Normalise IPv6-mapped IPv4 (::ffff:1.2.3.4 → 1.2.3.4)
  if (rawIp.startsWith('::ffff:')) rawIp = rawIp.substring(7);
  if (!rawIp || rawIp === '::1') rawIp = '127.0.0.1';

  return rawIp;
}

/**
 * Returns `true` if `clientIp` matches any entry in a comma-separated list of
 * allowed IP addresses/prefixes (supports `*` wildcard suffix and trailing `.`).
 */
export function isIpMatching(clientIp: string, allowedIpsStr: string): boolean {
  if (!clientIp || !allowedIpsStr) return false;
  const list = allowedIpsStr.split(',').map(s => s.trim().toLowerCase()).filter(Boolean);
  const clean = clientIp.toLowerCase();
  for (const item of list) {
    if (item === clean) return true;
    if (
      (item === '127.0.0.1' || item === '::1' || item === 'localhost') &&
      (clean === '127.0.0.1' || clean === '::1')
    ) return true;
    if (item.endsWith('*') && clean.startsWith(item.slice(0, -1))) return true;
    if (item.endsWith('.') && clean.startsWith(item)) return true;
  }
  return false;
}

/**
 * Parses a database date value (string or Date) into a JavaScript `Date`,
 * correctly handling both PostgreSQL UTC ISO strings and SQLite datetime strings.
 */
export function parseDbDate(raw: string | Date): Date {
  if (!raw) return new Date();
  if (raw instanceof Date) return raw;
  let s = String(raw).trim();
  if (s.endsWith('Z') || s.includes('+') || (s.includes('-') && s.lastIndexOf('-') > 10)) {
    return new Date(s);
  }
  if (s.includes('T')) return new Date(s + 'Z');
  return new Date(s.replace(' ', 'T') + 'Z');
}

// ─────────────────────────────────────────────────────────────────────────────
// Main factory
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Initialises the database, registers all API routes, and starts the per-minute
 * reminder cron job.
 *
 * @returns The configured Express `Application` instance. Listening is handled
 *          externally by `server.ts` so that Next.js can be attached first.
 */
export async function createBackendApp(): Promise<express.Application> {
  // ── App setup ─────────────────────────────────────────────────────────────
  const app = express();

  // Security headers for all responses
  app.use((_req, res, next) => {
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('X-Frame-Options', 'DENY');
    res.setHeader('X-XSS-Protection', '1; mode=block');
    res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
    next();
  });

  app.use(express.json());
  app.use(express.static(path.join(__dirname, '../public')));

  // ── Database & email startup ───────────────────────────────────────────────
  await initDB();

  // Load Brevo API key from the settings table if not already in env
  try {
    const savedBrevoRow = await dbGet(`SELECT value FROM settings WHERE key = 'brevo_api_key'`) as any;
    if (savedBrevoRow?.value && !process.env.BREVO_API_KEY) {
      process.env.BREVO_API_KEY = savedBrevoRow.value;
      console.log('[Brevo] Loaded BREVO_API_KEY from database settings.');
    } else if (process.env.BREVO_API_KEY) {
      console.log('[Brevo] BREVO_API_KEY loaded from environment variable.');
    } else {
      console.warn('[Brevo] BREVO_API_KEY not found — emails will be simulated only.');
    }
  } catch (e) {
    console.error('[Brevo] Settings load error:', e);
  }

  // ── Auth middleware ────────────────────────────────────────────────────────

  /**
   * Verifies a JWT from the Authorization header, cookie, query string, or
   * request body. Attaches the decoded payload to `req.user` on success.
   */
  const authenticateToken = (
    req: express.Request,
    res: express.Response,
    next: express.NextFunction,
  ) => {
    let token = '';
    const authHeader = req.headers['authorization'];
    if (authHeader?.startsWith('Bearer ')) token = authHeader.split(' ')[1] || '';
    else if (authHeader) token = authHeader;

    if (!token && req.headers.cookie) {
      const match = req.headers.cookie.match(/(?:^|;\s*)token=([^;]+)/);
      if (match?.[1]) token = decodeURIComponent(match[1]);
    }
    if (!token && req.query?.token)  token = String(req.query.token);
    if (!token && req.body?.token)   token = String(req.body.token);

    if (!token) return res.status(401).json({ error: 'Access denied. Token required.' });

    jwt.verify(token, JWT_SECRET, (err: any, user: any) => {
      if (err) return res.status(403).json({ error: 'Invalid or expired token.' });
      (req as any).user = user;
      next();
    });
  };

  /** Middleware factory that restricts a route to a specific role (e.g. `"Admin"`). */
  const requireRole = (role: string) =>
    (req: express.Request, res: express.Response, next: express.NextFunction) => {
      const user = (req as any).user;
      if (!user || user.role !== role) {
        return res.status(403).json({ error: `Access denied. ${role} role required.` });
      }
      next();
    };

  // ── Login (rate-limited, public) ──────────────────────────────────────────
  /** In-memory map for login attempt tracking per IP. Resets every 15 minutes. */
  const loginAttempts = new Map<string, { count: number; resetTime: number }>();

  app.post('/api/auth/login', async (req, res) => {
    const ip = req.ip || req.socket.remoteAddress || 'unknown';
    const now = Date.now();
    const attempt = loginAttempts.get(ip) || { count: 0, resetTime: now + 15 * 60 * 1000 };

    if (now > attempt.resetTime) {
      attempt.count = 1;
      attempt.resetTime = now + 15 * 60 * 1000;
    } else {
      attempt.count++;
    }
    loginAttempts.set(ip, attempt);

    if (attempt.count > 10) {
      return res.status(429).json({ error: 'Too many login attempts. Try again in 15 minutes.' });
    }

    const { email, password } = req.body;
    const cleanEmail    = (email    || '').trim().toLowerCase();
    const cleanPassword = (password || '').trim();
    if (!cleanEmail || !cleanPassword) {
      return res.status(400).json({ error: 'Email and password are required.' });
    }

    try {
      const member = await dbGet(
        `SELECT * FROM members WHERE LOWER(TRIM(email)) = ?`,
        [cleanEmail],
      ) as any;
      if (!member) return res.status(401).json({ error: 'Invalid credentials.' });

      const valid = await bcrypt.compare(cleanPassword, member.password_hash || '');
      if (!valid) return res.status(401).json({ error: 'Invalid credentials.' });

      const token = jwt.sign(
        { id: member.id, email: member.email, role: member.role, name: member.name, tenant_id: member.tenant_id },
        JWT_SECRET,
        { expiresIn: '7d' },
      );

      const { password_hash, ...memberData } = member;
      res.json({ token, user: memberData });
    } catch (err: any) {
      res.status(500).json({ error: 'Login failed.', details: err.message });
    }
  });

  // ── Global auth guard (applied after public endpoints) ───────────────────
  /** Public routes that are exempt from JWT authentication. */
  const PUBLIC_PATHS = [
    '/auth/login',
    '/attendance/wifi-webhook',
    '/attendance/wifi-status',
    '/attendance/client-ping',
    '/attendance/download-script',
    '/attendance/active-devices',
    '/settings/wifi',
  ];

  app.use('/api', (req, res, next) => {
    if (PUBLIC_PATHS.some(p => req.path.startsWith(p))) return next();
    authenticateToken(req, res, next);
  });

  // Inject tenant context for all authenticated routes
  app.use('/api', (req, res, next) => {
    const user = (req as any).user;
    if (user && user.tenant_id) {
      tenantStorage.run(user.tenant_id, next);
    } else {
      next();
    }
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── MEMBERS ───────────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  /** GET /api/members — returns all members (sans password hashes). */
  app.get('/api/members', async (_req, res) => {
    res.json(await dbAll(
      `SELECT id, name, email, role, avatar_color, created_at FROM members ORDER BY name`,
    ));
  });

  /** POST /api/members — creates a new member (Admin only). */
  app.post('/api/members', requireRole('Admin'), async (req, res) => {
    const { name, email, role, avatar_color, password } = req.body;
    if (!name) return res.status(400).json({ error: 'Name is required.' });

    const colors = ['#4f7eff', '#2dd4a0', '#ff4d6a', '#ff9f40', '#a78bfa', '#f472b6'];
    const color   = avatar_color || colors[Math.floor(Math.random() * colors.length)];
    const pwdHash = await bcrypt.hash(password || 'password123', 10);

    const { lastID } = await dbRun(
      `INSERT INTO members(name, email, role, avatar_color, password_hash) VALUES (?, ?, ?, ?, ?)`,
      [name, email || '', role || 'Employee', color, pwdHash],
    );
    res.json({ id: lastID });
  });

  /** PUT /api/members/:id — updates member details (Admin only). */
  app.put('/api/members/:id', requireRole('Admin'), async (req, res) => {
    const { name, email, role, password } = req.body;
    if (!name) return res.status(400).json({ error: 'Name is required.' });

    if (password) {
      const pwdHash = await bcrypt.hash(password, 10);
      await dbRun(
        `UPDATE members SET name = ?, email = ?, role = ?, password_hash = ? WHERE id = ?`,
        [name, email || '', role || 'Employee', pwdHash, req.params.id],
      );
    } else {
      await dbRun(
        `UPDATE members SET name = ?, email = ?, role = ? WHERE id = ?`,
        [name, email || '', role || 'Employee', req.params.id],
      );
    }
    res.json({ success: true });
  });

  /** DELETE /api/members/:id — removes a member and unassigns their tasks (Admin only). */
  app.delete('/api/members/:id', requireRole('Admin'), async (req, res) => {
    await dbRun(`UPDATE tasks SET assigned_to = NULL WHERE assigned_to = ?`, [req.params.id]);
    await dbRun(`DELETE FROM members WHERE id = ?`, [req.params.id]);
    res.json({ success: true });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── TASKS ─────────────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * GET /api/tasks — returns tasks for the requesting date.
   *   Admins see all tasks; Employees see only their own.
   */
  app.get('/api/tasks', async (req, res) => {
    const requestingUser = (req as any).user;
    const date           = (req.query.date as string) || new Date().toISOString().split('T')[0];
    const includeArchived = req.query.archived === 'true';
    const archiveFilter   = includeArchived
      ? 't.is_archived = 1'
      : '(t.is_archived = 0 OR t.is_archived IS NULL)';

    const baseJoin = `
      SELECT t.*, m.name AS assignee_name, m.avatar_color AS assignee_color
      FROM tasks t
      LEFT JOIN members m ON t.assigned_to = m.id
    `;
    const dateFilter = `(date(t.task_date) = date(?) OR (date(t.task_date) < date(?) AND t.status != 'DONE'))`;
    const orderBy    = `ORDER BY t.task_date DESC, t.created_at DESC`;

    if (requestingUser?.role !== 'Admin') {
      return res.json(await dbAll(
        `${baseJoin} WHERE ${dateFilter} AND ${archiveFilter} AND t.assigned_to = ? ${orderBy}`,
        [date, date, requestingUser?.id],
      ));
    }

    res.json(await dbAll(
      `${baseJoin} WHERE ${dateFilter} AND ${archiveFilter} ${orderBy}`,
      [date, date],
    ));
  });

  /** POST /api/tasks — creates a task and sends assignment email (Admin only). */
  app.post('/api/tasks', requireRole('Admin'), async (req, res) => {
    const {
      title, description, deadline, priority, assigned_to,
      task_date, action_type, recipient, status,
      notify_email, reminder_days, reminder_hours, reminder_minutes,
    } = req.body;

    if (!title) return res.status(400).json({ error: 'Title is required.' });

    const date      = task_date || new Date().toISOString().split('T')[0];
    const remDays   = reminder_days   != null && reminder_days   !== '' ? Number(reminder_days)   : null;
    const remHours  = reminder_hours  != null && reminder_hours  !== '' ? Number(reminder_hours)  : null;
    const remMins   = reminder_minutes != null && reminder_minutes !== '' ? Number(reminder_minutes) : null;
    const hasReminder = (remDays && remDays > 0) || (remHours && remHours > 0) || (remMins && remMins > 0);
    const initialStatus = status || 'DONE';

    const { lastID } = await dbRun(
      `INSERT INTO tasks(title, description, deadline, priority, assigned_to, task_date, action_type, recipient, status, notify_email, reminder_days, reminder_hours, reminder_minutes)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [title, description || '', deadline || null, priority || 'GREEN', assigned_to || null, date,
       action_type || 'STUDY', recipient || '', initialStatus, notify_email ? 1 : 1,
       remDays, remHours, remMins],
    );

    const newTask = await dbGet(
      `SELECT t.*, m.name AS assignee_name, m.avatar_color AS assignee_color
       FROM tasks t LEFT JOIN members m ON t.assigned_to = m.id
       WHERE t.id = ?`,
      [lastID],
    ) as any;

    // In-app notification + email for the assignee
    if (assigned_to) {
      const assignee = await dbGet(`SELECT name FROM members WHERE id = ?`, [assigned_to]) as any;
      await notifyMember(assigned_to, `New Task Assigned: "${title}"`, '/dashboard');

      const emails    = await resolveMemberNotificationEmails(assigned_to);
      const emailHtml = buildAolErpHtml('New Task Assigned', [
        { label: 'Name',     value: assignee?.name || 'Assigned Member' },
        { label: 'Task',     value: title },
        { label: 'Status',   value: initialStatus },
        { label: 'Deadline', value: deadline ? new Date(deadline).toLocaleString('en-GB') : 'No Deadline' },
        { label: 'Contact',  value: recipient || '—' },
      ]);
      sendBrevoEmail({
        to: emails,
        subject: `ERP: New Task - ${title}`,
        htmlContent: emailHtml,
      }).catch(console.error);

      // Schedule automatic 24h & 15h email reminders if no custom reminder is set
      if (deadline && !hasReminder) {
        schedule24And15HourReminders({
          entityType: 'task', entityId: lastID,
          targetDateTime: deadline,
          recipientEmails: emails,
          title: `Task Deadline: ${title}`,
          rows: [
            { label: 'Name',     value: assignee?.name || 'Assigned Member' },
            { label: 'Task',     value: title },
            { label: 'Deadline', value: new Date(deadline).toLocaleString('en-GB') },
          ],
        }).catch(console.error);
      }
    }

    // Schedule custom day / hour / minute email reminders when set
    if (hasReminder && deadline) {
      const emails = await resolveMemberNotificationEmails(assigned_to || 'Admin');
      scheduleCustomReminders({
        entityType: 'task', entityId: lastID,
        targetDateTime: deadline,
        recipientEmails: emails,
        title,
        rows: [
          { label: 'Task',     value: title },
          { label: 'Assignee', value: newTask?.assignee_name || '—' },
          { label: 'Deadline', value: new Date(deadline).toLocaleString('en-GB') },
        ],
        reminderDays: remDays, reminderHours: remHours, reminderMinutes: remMins,
      }).catch(console.error);

      await notifyReminderConfigured({
        entityLabel: 'Task', title, link: '/dashboard',
        remDays, remHours, remMins,
        alsoMemberId: assigned_to ? Number(assigned_to) : null,
      });
    }

    res.status(201).json(newTask);
  });

  /**
   * PATCH /api/tasks/:id — partial update.
   *   Employees can only update `status` on their own tasks.
   *   Admins can update all fields, but cannot change status unless they are the assignee.
   */
  app.patch('/api/tasks/:id', async (req, res) => {
    const requestingUser = (req as any).user;
    const oldTask = await dbGet(
      `SELECT t.*, m.name AS assignee_name FROM tasks t LEFT JOIN members m ON t.assigned_to = m.id WHERE t.id = ?`,
      [req.params.id],
    ) as any;

    if (requestingUser?.role !== 'Admin') {
      if (!oldTask || Number(oldTask.assigned_to) !== Number(requestingUser?.id)) {
        return res.status(403).json({ error: 'You can only update tasks assigned to you.' });
      }
      if (Object.keys(req.body).some(k => k !== 'status')) {
        return res.status(403).json({ error: 'Employees may only update task status.' });
      }
    } else if ('status' in req.body) {
      // Admins should not be able to mark tasks as DONE on behalf of the assignee
      if (Number(oldTask?.assigned_to) !== Number(requestingUser?.id)) {
        delete req.body.status;
      }
    }

    const ALLOWED_FIELDS = [
      'status', 'priority', 'title', 'description', 'deadline', 'assigned_to',
      'action_type', 'recipient', 'is_archived', 'notify_email',
      'reminder_days', 'reminder_hours', 'reminder_minutes',
    ];
    const updates: string[] = [];
    const values:  any[]    = [];
    for (const key of ALLOWED_FIELDS) {
      if (key in req.body) {
        updates.push(`${key} = ?`);
        values.push(req.body[key] ?? null);
      }
    }
    if (updates.length > 0) {
      values.push(req.params.id);
      await dbRun(`UPDATE tasks SET ${updates.join(', ')} WHERE id = ?`, values);
    }

    const updatedTask = await dbGet(
      `SELECT t.*, m.name AS assignee_name, m.avatar_color AS assignee_color
       FROM tasks t LEFT JOIN members m ON t.assigned_to = m.id WHERE t.id = ?`,
      [req.params.id],
    ) as any;

    // Re-schedule custom email reminders if relevant fields changed
    const reminderChanged = 'reminder_days' in req.body || 'reminder_hours' in req.body ||
      'reminder_minutes' in req.body || 'deadline' in req.body || 'notify_email' in req.body;

    if (updatedTask && reminderChanged) {
      const hasReminder =
        Number(updatedTask.reminder_days)    > 0 ||
        Number(updatedTask.reminder_hours)   > 0 ||
        Number(updatedTask.reminder_minutes) > 0;

      if (updatedTask.notify_email && hasReminder && updatedTask.deadline) {
        const emails = await resolveMemberNotificationEmails(updatedTask.assigned_to || 'Admin');
        scheduleCustomReminders({
          entityType: 'task', entityId: Number(req.params.id),
          targetDateTime: updatedTask.deadline,
          recipientEmails: emails,
          title: updatedTask.title,
          rows: [
            { label: 'Task',     value: updatedTask.title },
            { label: 'Assignee', value: updatedTask.assignee_name || '—' },
            { label: 'Deadline', value: new Date(updatedTask.deadline).toLocaleString('en-GB') },
          ],
          reminderDays:    updatedTask.reminder_days,
          reminderHours:   updatedTask.reminder_hours,
          reminderMinutes: updatedTask.reminder_minutes,
        }).catch(console.error);
      } else {
        dbRun(
          `DELETE FROM email_jobs WHERE entity_type = ? AND entity_id = ? AND status = ?`,
          ['task', req.params.id, 'PENDING'],
        ).catch(() => {});
      }
    }

    // In-app notification when task status changes
    if (oldTask && updatedTask && req.body.status && req.body.status !== oldTask.status) {
      const msg = `Task Status: "${updatedTask.title}" marked as ${req.body.status} by ${requestingUser?.name || 'employee'}.`;
      const admins = await dbAll(`SELECT id FROM members WHERE role = 'Admin'`) as any[];
      for (const a of admins) {
        await dbRun(
          `INSERT INTO notifications(member_id, message, link) VALUES (?, ?, ?)`,
          [a.id, msg, '/dashboard'],
        );
      }
    }

    // In-app notification when task is re-assigned
    if (oldTask && req.body.assigned_to && req.body.assigned_to !== oldTask.assigned_to) {
      await notifyMember(
        req.body.assigned_to,
        `You have been assigned a task: "${updatedTask?.title}"`,
        '/dashboard',
      );
    }

    res.json(updatedTask);
  });

  /** DELETE /api/tasks/:id — hard-deletes a task (Admin only). */
  app.delete('/api/tasks/:id', requireRole('Admin'), async (req, res) => {
    await dbRun(`DELETE FROM tasks WHERE id = ?`, [req.params.id]);
    res.json({ ok: true });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── EMAIL (BREVO) SETTINGS ────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * POST /api/settings/email — saves the Brevo API key to the settings table
   * and applies it immediately without requiring a server restart.
   */
  app.post('/api/settings/email', requireRole('Admin'), async (req, res) => {
    const { api_key, sender_email } = req.body;
    if (!api_key?.trim()) return res.status(400).json({ error: 'api_key is required.' });

    const cleanKey = api_key.trim();
    const upsert = isPostgres()
      ? `INSERT INTO settings(key, value) VALUES(?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value`
      : `INSERT OR REPLACE INTO settings(key, value) VALUES(?, ?)`;

    await dbRun(upsert, ['brevo_api_key', cleanKey]).catch(async () => {
      await dbRun(`INSERT OR REPLACE INTO settings(key, value) VALUES(?, ?)`, ['brevo_api_key', cleanKey]);
    });

    if (sender_email?.trim()) {
      await dbRun(upsert, ['brevo_sender_email', sender_email.trim()]).catch(async () => {
        await dbRun(`INSERT OR REPLACE INTO settings(key, value) VALUES(?, ?)`, ['brevo_sender_email', sender_email.trim()]);
      });
    }

    // Apply without restart
    process.env.BREVO_API_KEY = cleanKey;
    if (sender_email?.trim()) process.env.BREVO_SENDER_EMAIL = sender_email.trim();

    console.log('[Email] API key updated via /api/settings/email');
    res.json({ success: true, message: 'Email settings saved and applied.' });
  });

  /**
   * POST /api/test-email — sends a test email to verify the Brevo integration (Admin only).
   */
  app.post('/api/test-email', requireRole('Admin'), async (req, res) => {
    const { to } = req.body;
    const recipient = to || '';
    if (!recipient) return res.status(400).json({ error: 'Recipient email address is required.' });

    try {
      const result = await sendBrevoEmail({
        to: recipient,
        subject: 'ERP-connect: Test Email',
        htmlContent: `<h2>Test Email</h2><p>Email notifications are working correctly. Sent at ${new Date().toISOString()}</p>`,
      });
      res.json({
        success: result.success,
        messageId: result.messageId,
        error: result.error,
        brevo_configured: !!process.env.BREVO_API_KEY,
        recipient,
      });
    } catch (err: any) {
      res.status(500).json({ success: false, error: err.message });
    }
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── ATTENDANCE ────────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  /** GET /api/attendance — returns all attendance records for a given date (Asia/Dhaka). */
  app.get('/api/attendance', async (req, res) => {
    const targetDate = (req.query.date as string) || new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' });
    const rows = await dbAll(
      `SELECT a.*, m.name AS member_name, m.avatar_color
       FROM attendance a LEFT JOIN members m ON a.member_id = m.id
       ORDER BY a.timestamp DESC`,
    ) as any[];
    const filtered = rows.filter(r => {
      const d = new Date(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' });
      return d === targetDate;
    });
    res.json(filtered);
  });

  /** GET /api/attendance/monthly — returns attendance records for a member in a given month (YYYY-MM). */
  app.get('/api/attendance/monthly', async (req, res) => {
    const { member_id, month } = req.query as { member_id: string; month: string };
    if (!member_id || !month) return res.status(400).json({ error: 'member_id and month (YYYY-MM) are required.' });

    const rows = await dbAll(
      `SELECT id, member_id, action_type, timestamp FROM attendance WHERE member_id = ? ORDER BY timestamp ASC`,
      [member_id],
    ) as any[];

    const filtered = rows
      .filter(r => parseDbDate(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' }).startsWith(month))
      .map(r => ({ ...r, att_date: parseDbDate(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' }) }));

    res.json(filtered);
  });

  /** GET /api/attendance/summary — returns all attendance records for a given month (YYYY-MM). */
  app.get('/api/attendance/summary', async (req, res) => {
    const { month } = req.query as { month: string };
    if (!month) return res.status(400).json({ error: 'month (YYYY-MM) is required.' });

    const rows = await dbAll(
      `SELECT id, member_id, action_type, timestamp FROM attendance ORDER BY timestamp ASC`,
    ) as any[];

    const filtered = rows
      .filter(r => parseDbDate(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' }).startsWith(month))
      .map(r => ({ ...r, att_date: parseDbDate(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' }) }));

    res.json(filtered);
  });

  /** POST /api/attendance — manually checks a member in or out. */
  app.post('/api/attendance', async (req, res) => {
    const { member_id, action_type } = req.body;
    if (!action_type || !['IN', 'OUT'].includes(action_type)) {
      return res.status(400).json({ error: 'action_type must be IN or OUT.' });
    }
    if (!member_id) return res.status(400).json({ error: 'member_id is required.' });

    const requestingUser = (req as any).user;
    if (requestingUser?.role !== 'Admin' && Number(member_id) !== Number(requestingUser?.id)) {
      return res.status(403).json({ error: 'You can only check in/out for yourself.' });
    }

    const todayDhaka = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' });

    // Duplicate check — scan recent records since SQLite date() may differ from Asia/Dhaka
    const recentRows = await dbAll(
      `SELECT id, action_type, timestamp FROM attendance WHERE member_id = ? AND action_type = ? ORDER BY id DESC LIMIT 20`,
      [member_id, action_type],
    ) as any[];
    const duplicate = recentRows.find(r => {
      try { return new Date(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' }) === todayDhaka; }
      catch { return false; }
    });
    if (duplicate) {
      return res.status(409).json({
        error: action_type === 'IN' ? 'Already checked in today.' : 'Already checked out today.',
        code: 'ALREADY_RECORDED',
      });
    }

    if (action_type === 'OUT') {
      const inRows = await dbAll(
        `SELECT id, timestamp FROM attendance WHERE member_id = ? AND action_type = 'IN' ORDER BY id DESC LIMIT 20`,
        [member_id],
      ) as any[];
      const hasCheckedIn = inRows.some(r => {
        try { return new Date(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' }) === todayDhaka; }
        catch { return false; }
      });
      if (!hasCheckedIn) return res.status(400).json({ error: 'Cannot check out before checking in.' });
    }

    const nowIso = new Date().toISOString();
    const { lastID } = await dbRun(
      `INSERT INTO attendance(member_id, action_type, timestamp) VALUES (?, ?, ?)`,
      [member_id, action_type, nowIso],
    );
    const rec = await dbGet(
      `SELECT a.*, m.name AS member_name FROM attendance a LEFT JOIN members m ON a.member_id = m.id WHERE a.id = ?`,
      [lastID],
    ) as any;

    const empName = rec?.member_name || 'An employee';
    const timeStr = new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true, timeZone: 'Asia/Dhaka' });
    await notifyAdmins(
      action_type === 'IN'
        ? `Check-In: ${empName} checked in at ${timeStr}.`
        : `Check-Out: ${empName} checked out at ${timeStr}.`,
      '/hr?tab=att',
    );

    res.status(201).json(rec);
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── WI-FI / LAPTOP AUTO-ATTENDANCE ───────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  /** GET /api/settings/wifi — returns the current office Wi-Fi settings. */
  app.get('/api/settings/wifi', async (req, res) => {
    const rows = await dbAll(
      `SELECT key, value FROM settings WHERE key IN ('office_wifi_ip','office_wifi_name','wifi_auto_attendance_enabled','auto_checkout_timeout_minutes')`,
    ) as any[];
    const config: Record<string, string> = {};
    rows.forEach(r => { config[r.key] = r.value; });
    const clientIp = getCleanClientIp(req);
    res.json({
      office_wifi_ip:               config['office_wifi_ip'] || '',
      office_wifi_name:             config['office_wifi_name'] || 'ERP-connect Office Wi-Fi',
      wifi_auto_attendance_enabled: config['wifi_auto_attendance_enabled'] !== 'false',
      auto_checkout_timeout_minutes: parseInt(config['auto_checkout_timeout_minutes'] || '40', 10),
      detected_client_ip:           clientIp,
      is_matching_office_wifi:      isIpMatching(clientIp, config['office_wifi_ip'] || ''),
    });
  });

  /** POST /api/settings/wifi — updates the office Wi-Fi settings (Admin only). */
  app.post('/api/settings/wifi', async (req, res) => {
    try {
      // Manual inline auth for this mixed-auth route
      let token = '';
      const authHeader = req.headers['authorization'];
      if (authHeader?.startsWith('Bearer ')) token = authHeader.split(' ')[1] || '';
      else if (authHeader) token = authHeader;
      if (!token && req.headers.cookie) {
        const m = req.headers.cookie.match(/(?:^|;\s*)token=([^;]+)/);
        if (m?.[1]) token = decodeURIComponent(m[1]);
      }
      if (!token && req.body?.token) token = req.body.token;
      if (!token && req.query?.token) token = String(req.query.token);
      if (token) {
        try { (req as any).user = jwt.verify(token, JWT_SECRET); } catch {}
      }
      const user = (req as any).user;
      if (user && user.role !== 'Admin') {
        return res.status(403).json({ error: 'Access denied. Admin role required.' });
      }

      const { office_wifi_ip, office_wifi_name, wifi_auto_attendance_enabled, auto_checkout_timeout_minutes } = req.body;
      const upsert = `INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value`;
      if (office_wifi_ip              !== undefined) await dbRun(upsert, ['office_wifi_ip',               String(office_wifi_ip).trim()]);
      if (office_wifi_name            !== undefined) await dbRun(upsert, ['office_wifi_name',             String(office_wifi_name).trim()]);
      if (wifi_auto_attendance_enabled !== undefined) await dbRun(upsert, ['wifi_auto_attendance_enabled', String(wifi_auto_attendance_enabled)]);
      if (auto_checkout_timeout_minutes !== undefined) await dbRun(upsert, ['auto_checkout_timeout_minutes', String(auto_checkout_timeout_minutes)]);

      res.json({ ok: true, message: 'Wi-Fi settings updated.' });
    } catch (err: any) {
      res.status(500).json({ error: 'Failed to save Wi-Fi settings: ' + (err?.message || 'Unknown error') });
    }
  });

  /** GET /api/attendance/wifi-status — public endpoint for browser-based Wi-Fi detection. */
  app.get('/api/attendance/wifi-status', async (req, res) => {
    const clientIp = getCleanClientIp(req);
    const rows = await dbAll(
      `SELECT key, value FROM settings WHERE key IN ('office_wifi_ip','office_wifi_name','wifi_auto_attendance_enabled')`,
    ) as any[];
    const config: Record<string, string> = {};
    rows.forEach(r => { config[r.key] = r.value; });
    res.json({
      client_ip:        clientIp,
      office_wifi_name: config['office_wifi_name'] || 'ERP-connect Office Wi-Fi',
      is_office_wifi:   isIpMatching(clientIp, config['office_wifi_ip'] || ''),
      is_auto_enabled:  config['wifi_auto_attendance_enabled'] !== 'false',
    });
  });

  /** POST /api/attendance/wifi-heartbeat — keeps a browser session presence alive and auto-checks in. */
  app.post('/api/attendance/wifi-heartbeat', async (req, res) => {
    const user = (req as any).user;
    if (!user?.id) return res.status(401).json({ error: 'Authentication required.' });

    const clientIp = getCleanClientIp(req);
    const rows = await dbAll(
      `SELECT key, value FROM settings WHERE key IN ('office_wifi_ip','wifi_auto_attendance_enabled')`,
    ) as any[];
    const config: Record<string, string> = {};
    rows.forEach(r => { config[r.key] = r.value; });

    const isMatching = isIpMatching(clientIp, config['office_wifi_ip'] || '');
    const isEnabled  = config['wifi_auto_attendance_enabled'] !== 'false';

    if (!isEnabled) return res.json({ is_office_wifi: isMatching, is_auto_enabled: false, auto_checked_in: false });

    const todayDhaka = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' });
    if (isMatching) {
      const rows = await dbAll(`SELECT * FROM attendance WHERE member_id = ?`, [user.id]) as any[];
      const existingIn = rows.find(r =>
        parseDbDate(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' }) === todayDhaka && r.action_type === 'IN',
      );
      let autoCheckedIn = false;
      if (!existingIn) {
        await dbRun(`INSERT INTO attendance(member_id, action_type, timestamp) VALUES (?, 'IN', ?)`, [user.id, new Date().toISOString()]);
        autoCheckedIn = true;
      }
      await dbRun(
        `INSERT INTO active_sessions(member_id, last_seen, ip, is_wifi) VALUES (?, CURRENT_TIMESTAMP, ?, 1)
         ON CONFLICT(member_id) DO UPDATE SET last_seen = CURRENT_TIMESTAMP, ip = excluded.ip, is_wifi = 1`,
        [user.id, clientIp],
      );
      return res.json({ success: true, is_office_wifi: true, auto_checked_in: autoCheckedIn });
    }

    res.json({ success: true, is_office_wifi: false, auto_checked_in: false });
  });

  /** POST /api/attendance/wifi-webhook — router webhook (MikroTik / UniFi CONNECT & DISCONNECT events). */
  app.post('/api/attendance/wifi-webhook', async (req, res) => {
    const { member_id, email, event, ip } = req.body;
    if (!event || !['CONNECT', 'DISCONNECT'].includes(event)) {
      return res.status(400).json({ error: 'event must be CONNECT or DISCONNECT.' });
    }

    let member: any = null;
    if (member_id) member = await dbGet(`SELECT * FROM members WHERE id = ?`, [member_id]);
    else if (email) member = await dbGet(`SELECT * FROM members WHERE LOWER(TRIM(email)) = LOWER(?)`, [email]);
    if (!member) return res.status(404).json({ error: 'Member not found.' });

    const todayDhaka = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' });
    const nowIso     = new Date().toISOString();
    const attRows    = await dbAll(`SELECT * FROM attendance WHERE member_id = ?`, [member.id]) as any[];
    const todayRows  = attRows.filter(r => parseDbDate(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' }) === todayDhaka);
    const existingIn  = todayRows.find(r => r.action_type === 'IN');
    const existingOut = todayRows.find(r => r.action_type === 'OUT');

    if (event === 'CONNECT') {
      if (!existingIn) {
        await dbRun(`INSERT INTO attendance(member_id, action_type, timestamp) VALUES (?, 'IN', ?)`, [member.id, nowIso]);
        await notifyAdmins(`Wi-Fi Auto Check-In: ${member.name} connected to Office Wi-Fi.`, '/hr?tab=att');
      }
      await dbRun(
        `INSERT INTO active_sessions(member_id, last_seen, ip, is_wifi) VALUES (?, CURRENT_TIMESTAMP, ?, 1)
         ON CONFLICT(member_id) DO UPDATE SET last_seen = CURRENT_TIMESTAMP, ip = excluded.ip, is_wifi = 1`,
        [member.id, ip || 'router-webhook'],
      );
      return res.json({ ok: true, action: 'IN', member_name: member.name });
    }

    // DISCONNECT
    if (existingIn && !existingOut) {
      await dbRun(`INSERT INTO attendance(member_id, action_type, timestamp) VALUES (?, 'OUT', ?)`, [member.id, nowIso]);
      await notifyAdmins(`Wi-Fi Auto Check-Out: ${member.name} disconnected from Office Wi-Fi.`, '/hr?tab=att');
    }
    await dbRun(`DELETE FROM active_sessions WHERE member_id = ?`, [member.id]);
    return res.json({ ok: true, action: 'OUT', member_name: member.name });
  });

  /** POST /api/attendance/client-ping — zero-browser laptop background agent endpoint. */
  app.post('/api/attendance/client-ping', async (req, res) => {
    const token = (req.headers.authorization?.replace(/^Bearer\s+/, '') || req.body.token || '') as string;
    if (!token) return res.status(401).json({ error: 'Token required.' });

    let user: any;
    try {
      user = jwt.verify(token, JWT_SECRET);
    } catch {
      return res.status(401).json({ error: 'Invalid or expired token.' });
    }

    const member = await dbGet(`SELECT * FROM members WHERE id = ?`, [user.id]) as any;
    if (!member) return res.status(404).json({ error: 'Member not found.' });

    const action    = req.body.action || 'PING';
    const hostname  = String(req.body.hostname || '').slice(0, 100);
    const osName    = String(req.body.os || req.body.os_name || 'Windows').slice(0, 50);
    const clientIp  = getCleanClientIp(req);
    const rows      = await dbAll(`SELECT key, value FROM settings WHERE key IN ('office_wifi_ip','wifi_auto_attendance_enabled')`) as any[];
    const config: Record<string, string> = {};
    rows.forEach(r => { config[r.key] = r.value; });
    const isMatching = isIpMatching(clientIp, config['office_wifi_ip'] || '');
    const isEnabled  = config['wifi_auto_attendance_enabled'] !== 'false';
    const todayDhaka = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' });
    const nowIso     = new Date().toISOString();
    const attRows    = await dbAll(`SELECT * FROM attendance WHERE member_id = ?`, [member.id]) as any[];
    const todayRecords  = attRows.filter(r => parseDbDate(r.timestamp).toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' }) === todayDhaka);
    const existingIn    = todayRecords.find(r => r.action_type === 'IN');
    const existingOut   = todayRecords.find(r => r.action_type === 'OUT');

    if (action === 'SHUTDOWN') {
      let autoCheckedOut = false;
      if (existingIn && !existingOut) {
        await dbRun(`INSERT INTO attendance(member_id, action_type, timestamp) VALUES (?, 'OUT', ?)`, [member.id, nowIso]);
        autoCheckedOut = true;
        await notifyAdmins(`Laptop Auto Check-Out: ${member.name} turned off laptop (${hostname || 'Workstation'}).`, '/hr?tab=att');
      }
      await dbRun(`DELETE FROM active_sessions WHERE member_id = ?`, [member.id]);
      return res.json({ success: true, action: 'OUT', auto_checked_out: autoCheckedOut, member_name: member.name });
    }

    if (isMatching && isEnabled) {
      let autoCheckedIn = false;
      if (!existingIn) {
        await dbRun(`INSERT INTO attendance(member_id, action_type, timestamp) VALUES (?, 'IN', ?)`, [member.id, nowIso]);
        autoCheckedIn = true;
        await notifyAdmins(`Laptop Auto Check-In: ${member.name} opened laptop (${hostname || 'Workstation'}).`, '/hr?tab=att');
      }
      await dbRun(
        `INSERT INTO active_sessions(member_id, last_seen, ip, is_wifi, hostname, os_name, device_type)
         VALUES (?, CURRENT_TIMESTAMP, ?, 1, ?, ?, 'LAPTOP')
         ON CONFLICT(member_id) DO UPDATE SET last_seen = CURRENT_TIMESTAMP, ip = excluded.ip, is_wifi = 1, hostname = excluded.hostname, os_name = excluded.os_name, device_type = 'LAPTOP'`,
        [member.id, clientIp, hostname, osName],
      );
      return res.json({ success: true, is_office_wifi: true, auto_checked_in: autoCheckedIn, member_name: member.name });
    }

    return res.json({ success: true, is_office_wifi: false, auto_checked_in: false, member_name: member.name });
  });

  /** GET /api/attendance/download-script — serves a personalised attendance agent installer. */
  app.get('/api/attendance/download-script', async (req, res) => {
    const token = (req.query.token as string || req.headers.authorization?.replace(/^Bearer\s+/, '') || '') as string;
    if (!token) return res.status(401).send('Authentication token required.');

    let user: any;
    try { user = jwt.verify(token, JWT_SECRET); }
    catch { return res.status(401).send('Invalid or expired token.'); }

    const member = await dbGet(`SELECT * FROM members WHERE id = ?`, [user.id]) as any;
    if (!member) return res.status(404).send('Member not found.');

    const renderHostname = process.env.RENDER_EXTERNAL_HOSTNAME;
    let serverUrl: string;
    if (renderHostname) {
      serverUrl = `https://${renderHostname}`;
    } else {
      const protocol = req.headers['x-forwarded-proto'] || (req.secure ? 'https' : 'http');
      serverUrl = `${protocol}://${req.headers.host || 'localhost:3000'}`;
    }

    const scriptToken = jwt.sign(
      { id: member.id, email: member.email, role: member.role, name: member.name, script: true },
      JWT_SECRET,
      { expiresIn: '365d' },
    );

    const os = (req.query.os as string || 'windows').toLowerCase();

    const psScript = `# ERP-connect ERP - Automated Attendance Agent
$serverUrl    = "${serverUrl}"
$token        = "${scriptToken}"
$employeeName = "${member.name}"
$hostname_val = $env:COMPUTERNAME
$os_val       = "Windows"

function Send-Ping($action) {
    try {
        $body = @{ token = $token; action = $action; hostname = $hostname_val; os = $os_val } | ConvertTo-Json
        return Invoke-RestMethod -Uri "$serverUrl/api/attendance/client-ping" \`
            -Method Post -Body $body -ContentType "application/json" -TimeoutSec 15
    } catch { return $null }
}

Register-EngineEvent -SourceIdentifier ([System.Management.Automation.PsEngineEvent]::Exiting) -Action {
    Send-Ping "SHUTDOWN"
} | Out-Null

$maxRetries = 6; $initResp = $null
for ($i = 0; $i -lt $maxRetries; $i++) {
    $initResp = Send-Ping "PING"
    if ($initResp) { break }
    Start-Sleep -Seconds 20
}

while ($true) {
    Start-Sleep -Seconds 60
    Send-Ping "PING" | Out-Null
}
`;

    if (os === 'ps1') {
      res.setHeader('Content-Type', 'text/plain');
      return res.send(psScript);
    }

    const psBase64  = Buffer.from(psScript, 'utf8').toString('base64');
    const vbsScript = `Set WshShell = CreateObject("WScript.Shell")\nWshShell.Run "powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & CreateObject("WScript.Shell").ExpandEnvironmentStrings("%LOCALAPPDATA%") & "\\ERP-connectERP\\aol-attendance.ps1""", 0, False\n`;
    const vbsBase64 = Buffer.from(vbsScript, 'utf8').toString('base64');

    const batContent = `@echo off
title ERP-connect ERP - Laptop Attendance Setup
set "TARGET_DIR=%LOCALAPPDATA%\\ERP-connectERP"
if not exist "%TARGET_DIR%" mkdir "%TARGET_DIR%"
set "PS_SCRIPT=%TARGET_DIR%\\aol-attendance.ps1"
set "VBS_SCRIPT=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\ERP-connectAttendance.vbs"
echo [1/3] Installing agent...
powershell -NoProfile -Command "$b64='${psBase64}'; [System.IO.File]::WriteAllBytes('%PS_SCRIPT%', [System.Convert]::FromBase64String($b64))"
echo [2/3] Registering startup...
powershell -NoProfile -Command "$b64='${vbsBase64}'; [System.IO.File]::WriteAllBytes('%VBS_SCRIPT%', [System.Convert]::FromBase64String($b64))"
echo [3/3] Starting agent...
wscript.exe "%VBS_SCRIPT%"
echo SUCCESS! Automated Attendance is active.
pause
`;

    if (os === 'windows' || os === 'bat') {
      res.setHeader('Content-Disposition', `attachment; filename="ERP-connect-Attendance-${member.name.replace(/[^a-zA-Z0-9]/g, '_')}.bat"`);
      res.setHeader('Content-Type', 'application/x-bat');
      return res.send(batContent);
    }

    // macOS / Linux shell script
    const shContent = `#!/bin/bash
# ERP-connect ERP - Attendance Agent for ${member.name}
SERVER_URL="${serverUrl}"
TOKEN="${scriptToken}"
HOSTNAME_VAL="$(hostname)"
OS_NAME="$(uname -s)"
send_ping() { curl -s -X POST "$SERVER_URL/api/attendance/client-ping" -H "Content-Type: application/json" -d "{\\"token\\":\\"$TOKEN\\",\\"action\\":\\"$1\\",\\"hostname\\":\\"$HOSTNAME_VAL\\",\\"os\\":\\"$OS_NAME\\"}" 2>/dev/null; }
trap 'send_ping "SHUTDOWN"' EXIT SIGTERM
send_ping "PING"
while true; do sleep 60; send_ping "PING" > /dev/null; done
`;
    res.setHeader('Content-Disposition', `attachment; filename="ERP-connect-Attendance-${member.name.replace(/[^a-zA-Z0-9]/g, '_')}.sh"`);
    res.setHeader('Content-Type', 'text/x-shellscript');
    return res.send(shContent);
  });

  /** GET /api/attendance/active-devices — lists currently active laptop/Wi-Fi sessions (Admin only). */
  app.get('/api/attendance/active-devices', async (req, res) => {
    // Inline auth (public-listed but functionally Admin-only)
    let token = '';
    const ah = req.headers['authorization'];
    if (ah?.startsWith('Bearer ')) token = ah.split(' ')[1] || '';
    else if (ah) token = ah;
    if (!token && req.headers.cookie) {
      const m = req.headers.cookie.match(/(?:^|;\s*)token=([^;]+)/);
      if (m?.[1]) token = decodeURIComponent(m[1]);
    }
    if (!token && req.query?.token) token = String(req.query.token);
    if (token) try { (req as any).user = jwt.verify(token, JWT_SECRET); } catch {}

    const rows = await dbAll(
      `SELECT a.*, m.name AS member_name, m.email, m.avatar_color
       FROM active_sessions a JOIN members m ON a.member_id = m.id
       WHERE a.is_wifi = 1 ORDER BY a.last_seen DESC`,
    );
    res.json(rows);
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── LEAVE REQUESTS ────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  /** GET /api/leaves — returns all leave requests (Admins) or member-specific (Employees). */
  app.get('/api/leaves', async (req, res) => {
    const memberId = req.query.member_id as string;
    if (memberId) {
      return res.json(await dbAll(
        `SELECT l.*, m.name AS member_name, m.avatar_color FROM leave_requests l JOIN members m ON l.member_id = m.id WHERE l.member_id = ? ORDER BY l.created_at DESC`,
        [memberId],
      ));
    }
    res.json(await dbAll(
      `SELECT l.*, m.name AS member_name, m.avatar_color FROM leave_requests l JOIN members m ON l.member_id = m.id ORDER BY l.created_at DESC`,
    ));
  });

  /** GET /api/leaves/monthly — returns leave requests for a member in a given month. */
  app.get('/api/leaves/monthly', async (req, res) => {
    const { member_id, month } = req.query as { member_id: string; month: string };
    if (!member_id || !month) return res.status(400).json({ error: 'member_id and month (YYYY-MM) are required.' });
    res.json(await dbAll(
      `SELECT * FROM leave_requests
       WHERE member_id = ? AND (start_date LIKE ? OR end_date LIKE ? OR (start_date <= ? AND end_date >= ?))
       ORDER BY start_date ASC`,
      [member_id, month + '%', month + '%', month + '-01', month + '-31'],
    ));
  });

  /** POST /api/leaves — creates a leave request and sends a notification email. */
  app.post('/api/leaves', async (req, res) => {
    const { member_id, leave_type, start_date, end_date, reason, notify_email, reminder_days, reminder_hours, reminder_minutes } = req.body;
    if (!member_id || !leave_type || !start_date || !end_date) {
      return res.status(400).json({ error: 'member_id, leave_type, start_date, and end_date are required.' });
    }

    const remDays  = reminder_days    != null && reminder_days    !== '' ? Number(reminder_days)    : null;
    const remHours = reminder_hours   != null && reminder_hours   !== '' ? Number(reminder_hours)   : null;
    const remMins  = reminder_minutes != null && reminder_minutes !== '' ? Number(reminder_minutes) : null;
    const hasReminder = (Number(remDays) > 0) || (Number(remHours) > 0) || (Number(remMins) > 0);
    const shouldNotify = notify_email !== undefined ? (notify_email ? 1 : 0) : (hasReminder ? 1 : 0);

    const { lastID } = await dbRun(
      `INSERT INTO leave_requests(member_id, leave_type, start_date, end_date, reason, notify_email, reminder_days, reminder_hours, reminder_minutes)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [member_id, leave_type, start_date, end_date, reason || '', shouldNotify, remDays, remHours, remMins],
    );

    const member = await dbGet(`SELECT name, email FROM members WHERE id = ?`, [member_id]) as any;
    await notifyAdmins(
      `Leave Request: ${member?.name || 'An employee'} requested ${leave_type} leave (${start_date} to ${end_date}).${reason ? ` Reason: "${reason}"` : ''}`,
      '/hr?tab=leave',
    );

    const recipientEmails = await resolveMemberNotificationEmails(member_id);
    const emailRows = [
      { label: 'Name',  value: member?.name || 'Employee' },
      { label: 'Leave', value: leave_type },
      { label: 'From',  value: `${start_date} to ${end_date}` },
      ...(reason ? [{ label: 'Reason', value: reason }] : []),
    ];
    sendBrevoEmail({
      to: recipientEmails,
      subject: `ERP: Leave Application - ${member?.name || 'Employee'} (${leave_type})`,
      htmlContent: buildAolErpHtml('Leave Application Submitted', emailRows),
    }).catch(console.error);

    let targetDateTime = String(start_date).trim();
    if (!targetDateTime.includes('T')) targetDateTime = `${targetDateTime}T09:00:00+06:00`;

    if (hasReminder) {
      scheduleCustomReminders({
        entityType: 'leave', entityId: lastID, targetDateTime,
        recipientEmails, title: `Leave: ${member?.name || 'Employee'} (${leave_type})`,
        rows: emailRows, reminderDays: remDays, reminderHours: remHours, reminderMinutes: remMins,
      }).catch(console.error);
      await notifyReminderConfigured({
        entityLabel: 'Leave', title: `${member?.name || 'Employee'} (${leave_type})`,
        link: '/hr?tab=leave', remDays, remHours, remMins, alsoMemberId: Number(member_id),
      });
    } else {
      schedule24And15HourReminders({
        entityType: 'leave', entityId: lastID, targetDateTime,
        recipientEmails, title: `Leave: ${member?.name || 'Employee'} (${leave_type})`,
        rows: emailRows,
      }).catch(console.error);
    }

    res.status(201).json(await dbGet(
      `SELECT l.*, m.name AS member_name FROM leave_requests l JOIN members m ON l.member_id = m.id WHERE l.id = ?`,
      [lastID],
    ));
  });

  /** PATCH /api/leaves/:id — updates leave status (approve/reject) or edits leave details. */
  app.patch('/api/leaves/:id', async (req, res) => {
    const { status, leave_type, start_date, end_date, reason, notify_email, reminder_days, reminder_hours, reminder_minutes } = req.body;

    if (status) {
      await dbRun(`UPDATE leave_requests SET status = ?, reviewed_at = CURRENT_TIMESTAMP WHERE id = ?`, [status, req.params.id]);
      const leaveRow = await dbGet(`SELECT * FROM leave_requests WHERE id = ?`, [req.params.id]) as any;
      if (leaveRow) {
        const member = await dbGet(`SELECT name FROM members WHERE id = ?`, [leaveRow.member_id]) as any;
        await notifyMember(leaveRow.member_id, `Your ${leaveRow.leave_type} leave request has been ${status}.`, '/hr?tab=leave');
        await notifyAdmins(`Leave Decision: ${member?.name || 'Employee'}'s ${leaveRow.leave_type} leave has been ${status}.`, '/hr?tab=leave');

        const recipientEmails = await resolveMemberNotificationEmails(leaveRow.member_id);
        const emailRows = [
          { label: 'Name',   value: member?.name || 'Employee' },
          { label: 'Leave',  value: leaveRow.leave_type },
          { label: 'Status', value: status },
          { label: 'From',   value: `${leaveRow.start_date} to ${leaveRow.end_date}` },
        ];
        sendBrevoEmail({
          to: recipientEmails,
          subject: `ERP: Leave Request ${status} - ${member?.name || 'Employee'}`,
          htmlContent: buildAolErpHtml(`Leave Request ${status}`, emailRows),
        }).catch(console.error);
      }
      return res.json(await dbGet(
        `SELECT l.*, m.name AS member_name, m.avatar_color FROM leave_requests l JOIN members m ON l.member_id = m.id WHERE l.id = ?`,
        [req.params.id],
      ));
    }

    // Field edit
    const current = await dbGet(`SELECT * FROM leave_requests WHERE id = ?`, [req.params.id]) as any;
    if (!current) return res.status(404).json({ error: 'Leave request not found.' });

    const nextDays  = reminder_days    !== undefined ? (reminder_days    === '' || reminder_days    === null ? null : Number(reminder_days))    : (current.reminder_days    ?? null);
    const nextHours = reminder_hours   !== undefined ? (reminder_hours   === '' || reminder_hours   === null ? null : Number(reminder_hours))   : (current.reminder_hours   ?? null);
    const nextMins  = reminder_minutes !== undefined ? (reminder_minutes === '' || reminder_minutes === null ? null : Number(reminder_minutes)) : (current.reminder_minutes ?? null);
    const hasReminder  = (Number(nextDays) > 0) || (Number(nextHours) > 0) || (Number(nextMins) > 0);
    const nextNotify   = notify_email !== undefined ? (notify_email ? 1 : 0) : (hasReminder ? 1 : (current.notify_email ? 1 : 0));

    await dbRun(
      `UPDATE leave_requests SET leave_type = ?, start_date = ?, end_date = ?, reason = ?, notify_email = ?, reminder_days = ?, reminder_hours = ?, reminder_minutes = ? WHERE id = ?`,
      [
        leave_type  !== undefined ? leave_type  : current.leave_type,
        start_date  !== undefined ? start_date  : current.start_date,
        end_date    !== undefined ? end_date    : current.end_date,
        reason      !== undefined ? reason      : current.reason,
        nextNotify, nextDays, nextHours, nextMins, req.params.id,
      ],
    );

    const leaveRow = await dbGet(
      `SELECT l.*, m.name AS member_name, m.avatar_color FROM leave_requests l JOIN members m ON l.member_id = m.id WHERE l.id = ?`,
      [req.params.id],
    ) as any;

    if (leaveRow?.notify_email && hasReminder && leaveRow.start_date) {
      const member = await dbGet(`SELECT name FROM members WHERE id = ?`, [leaveRow.member_id]) as any;
      let targetDateTime = String(leaveRow.start_date).trim();
      if (!targetDateTime.includes('T')) targetDateTime = `${targetDateTime}T09:00:00+06:00`;
      const recipientEmails = await resolveMemberNotificationEmails(leaveRow.member_id);
      scheduleCustomReminders({
        entityType: 'leave', entityId: Number(req.params.id), targetDateTime,
        recipientEmails, title: `Updated Leave: ${member?.name || 'Employee'} (${leaveRow.leave_type})`,
        rows: [
          { label: 'Name',  value: member?.name || 'Employee' },
          { label: 'Leave', value: leaveRow.leave_type },
          { label: 'From',  value: `${leaveRow.start_date} to ${leaveRow.end_date}` },
        ],
        reminderDays: leaveRow.reminder_days, reminderHours: leaveRow.reminder_hours, reminderMinutes: leaveRow.reminder_minutes,
      }).catch(console.error);
    } else {
      dbRun(`DELETE FROM email_jobs WHERE entity_type = ? AND entity_id = ? AND status = ?`, ['leave', req.params.id, 'PENDING']).catch(() => {});
    }

    return res.json(leaveRow);
  });

  /** DELETE /api/leaves/:id — deletes a leave request and its scheduled email jobs (Admin only). */
  app.delete('/api/leaves/:id', requireRole('Admin'), async (req, res) => {
    await dbRun(`DELETE FROM email_jobs WHERE entity_type = ? AND entity_id = ?`, ['leave', Number(req.params.id)]);
    await dbRun(`DELETE FROM leave_requests WHERE id = ?`, [req.params.id]);
    res.json({ ok: true });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── IN-APP NOTIFICATIONS ──────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  /** GET /api/notifications — returns unread notifications for a member. */
  app.get('/api/notifications', async (req, res) => {
    const memberId = req.query.member_id;
    if (!memberId) return res.json([]);
    const falseVal = isPostgres() ? 'false' : '0';
    res.json(await dbAll(
      `SELECT * FROM notifications WHERE member_id = ? AND (is_read = ${falseVal} OR is_read IS NULL) ORDER BY created_at DESC LIMIT 50`,
      [Number(memberId)],
    ));
  });

  /** PATCH /api/notifications/:id/read — marks a single notification as read. */
  app.patch('/api/notifications/:id/read', async (req, res) => {
    const trueVal = isPostgres() ? 'true' : '1';
    await dbRun(`UPDATE notifications SET is_read = ${trueVal} WHERE id = ?`, [Number(req.params.id)]);
    res.json({ ok: true });
  });

  /** PATCH /api/notifications/read-all — marks all of a member's notifications as read. */
  app.patch('/api/notifications/read-all', async (req, res) => {
    const { member_id } = req.body;
    if (!member_id) return res.status(400).json({ error: 'member_id is required.' });
    const trueVal = isPostgres() ? 'true' : '1';
    await dbRun(`UPDATE notifications SET is_read = ${trueVal} WHERE member_id = ?`, [Number(member_id)]);
    res.json({ ok: true });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── EXPENSES ──────────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  app.get('/api/expense-categories', requireRole('Admin'), async (_req, res) => {
    res.json(await dbAll(`SELECT * FROM expense_categories ORDER BY name`));
  });

  app.get('/api/expenses', requireRole('Admin'), async (req, res) => {
    const month = (req.query.month as string) || new Date().toISOString().substring(0, 7);
    res.json(await dbAll(
      `SELECT e.*, c.name AS category_name, c.color AS category_color, c.budget_limit, m.name AS member_name
       FROM expenses e
       LEFT JOIN expense_categories c ON e.category_id = c.id
       LEFT JOIN members m ON e.entered_by = m.id
       WHERE e.expense_date LIKE ? ORDER BY e.expense_date DESC`,
      [month + '%'],
    ));
  });

  app.get('/api/expenses/summary', requireRole('Admin'), async (req, res) => {
    const month = (req.query.month as string) || new Date().toISOString().substring(0, 7);
    res.json(await dbAll(
      `SELECT c.id, c.name, c.color, c.budget_limit, COALESCE(SUM(e.amount), 0) AS total
       FROM expense_categories c
       LEFT JOIN expenses e ON e.category_id = c.id AND e.expense_date LIKE ?
       GROUP BY c.id ORDER BY total DESC`,
      [month + '%'],
    ));
  });

  app.get('/api/expenses/daily-summary', requireRole('Admin'), async (req, res) => {
    const month = (req.query.month as string) || new Date().toISOString().substring(0, 7);
    const days = await dbAll(
      `SELECT expense_date AS date, SUM(amount) AS total FROM expenses WHERE expense_date LIKE ? GROUP BY expense_date ORDER BY expense_date DESC`,
      [month + '%'],
    ) as any[];
    const result = [];
    for (const day of days) {
      const heads = await dbAll(
        `SELECT expense_head, SUM(amount) AS amt FROM expenses WHERE expense_date = ? AND expense_head != '' GROUP BY expense_head ORDER BY amt DESC LIMIT 3`,
        [day.date],
      ) as any[];
      result.push({ date: day.date, total: day.total, top_heads: heads.map((h: any) => h.expense_head) });
    }
    res.json(result);
  });

  app.post('/api/expenses', requireRole('Admin'), async (req, res) => {
    const { category_id, amount, description, entered_by, expense_date, company_name, expense_head, payment_method } = req.body;
    if (amount === undefined || amount === null) return res.status(400).json({ error: 'amount is required.' });
    const date = expense_date || new Date().toISOString().split('T')[0];
    const { lastID } = await dbRun(
      `INSERT INTO expenses(category_id, amount, description, entered_by, expense_date, company_name, expense_head, payment_method)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      [category_id || null, amount, description || '', entered_by || null, date, company_name || '', expense_head || '', payment_method || 'Cash'],
    );
    res.status(201).json(await dbGet(
      `SELECT e.*, c.name AS category_name FROM expenses e LEFT JOIN expense_categories c ON e.category_id = c.id WHERE e.id = ?`,
      [lastID],
    ));
  });

  app.patch('/api/expenses/:id', requireRole('Admin'), async (req, res) => {
    const { amount, description, expense_date, company_name, expense_head, payment_method } = req.body;
    const parts: string[] = []; const values: any[] = [];
    if (amount       !== undefined) { parts.push('amount = ?');         values.push(Number(amount)); }
    if (description  !== undefined) { parts.push('description = ?');    values.push(description); }
    if (expense_date)               { parts.push('expense_date = ?');    values.push(expense_date); }
    if (company_name)               { parts.push('company_name = ?');    values.push(company_name); }
    if (expense_head)               { parts.push('expense_head = ?');    values.push(expense_head); }
    if (payment_method)             { parts.push('payment_method = ?');  values.push(payment_method); }
    if (parts.length === 0) return res.status(400).json({ error: 'No fields to update.' });
    values.push(req.params.id);
    await dbRun(`UPDATE expenses SET ${parts.join(', ')} WHERE id = ?`, values);
    res.json(await dbGet(`SELECT * FROM expenses WHERE id = ?`, [req.params.id]));
  });

  app.delete('/api/expenses/:id', requireRole('Admin'), async (req, res) => {
    await dbRun(`DELETE FROM expenses WHERE id = ?`, [req.params.id]);
    res.json({ ok: true });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── CREDENTIALS ───────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  app.get('/api/credentials', requireRole('Admin'), async (_req, res) => {
    res.json(await dbAll(`SELECT * FROM credentials ORDER BY created_at DESC`));
  });

  app.post('/api/credentials', requireRole('Admin'), async (req, res) => {
    const { name, cred_type, url, username, cost, expiry_date, last_changed_date, notify_email, reminder_days, reminder_hours, reminder_minutes } = req.body;
    if (!name) return res.status(400).json({ error: 'Name is required.' });

    const remDays  = reminder_days    != null && reminder_days    !== '' ? Number(reminder_days)    : null;
    const remHours = reminder_hours   != null && reminder_hours   !== '' ? Number(reminder_hours)   : null;
    const remMins  = reminder_minutes != null && reminder_minutes !== '' ? Number(reminder_minutes) : null;
    const hasReminder = (remDays && remDays > 0) || (remHours && remHours > 0) || (remMins && remMins > 0);
    const shouldNotify = notify_email ? 1 : (hasReminder ? 1 : 0);
    const legacyDays = remDays && remDays > 0 ? String(remDays) : '';

    const { lastID } = await dbRun(
      `INSERT INTO credentials(name, cred_type, url, username, cost, expiry_date, last_changed_date, reminder_days_before, notify_email, reminder_days, reminder_hours, reminder_minutes)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [name, cred_type || 'OTHER', url || '', username || '', cost || 0, expiry_date || null, last_changed_date || null, legacyDays, shouldNotify, remDays, remHours, remMins],
    );

    if (shouldNotify && hasReminder && expiry_date) {
      const adminEmails = await resolveMemberNotificationEmails('Admin');
      scheduleCustomReminders({
        entityType: 'credential', entityId: lastID,
        targetDateTime: `${expiry_date}T09:00:00+06:00`,
        recipientEmails: adminEmails, title: `Credential Expiry: ${name}`,
        rows: [
          { label: 'Activity',    value: name },
          { label: 'User',        value: username || '—' },
          { label: 'Expiry Date', value: expiry_date },
          { label: 'URL',         value: url || '—' },
        ],
        reminderDays: remDays, reminderHours: remHours, reminderMinutes: remMins,
      }).catch(console.error);
      await notifyReminderConfigured({ entityLabel: 'Credential', title: name, link: '/credentials', remDays, remHours, remMins });
    }

    res.status(201).json(await dbGet(`SELECT * FROM credentials WHERE id = ?`, [lastID]));
  });

  app.patch('/api/credentials/:id', requireRole('Admin'), async (req, res) => {
    const { name, cred_type, url, username, cost, expiry_date, last_changed_date, notify_email, reminder_days, reminder_hours, reminder_minutes } = req.body;
    const current = await dbGet(`SELECT * FROM credentials WHERE id = ?`, [req.params.id]) as any;
    if (!current) return res.status(404).json({ error: 'Credential not found.' });

    const nextDays  = reminder_days    !== undefined ? (reminder_days    === '' || reminder_days    === null ? null : Number(reminder_days))    : (current.reminder_days    ?? null);
    const nextHours = reminder_hours   !== undefined ? (reminder_hours   === '' || reminder_hours   === null ? null : Number(reminder_hours))   : (current.reminder_hours   ?? null);
    const nextMins  = reminder_minutes !== undefined ? (reminder_minutes === '' || reminder_minutes === null ? null : Number(reminder_minutes)) : (current.reminder_minutes ?? null);
    const hasReminder  = (Number(nextDays) > 0) || (Number(nextHours) > 0) || (Number(nextMins) > 0);
    const nextNotify   = notify_email !== undefined ? (notify_email ? 1 : 0) : (hasReminder ? 1 : (current.notify_email || 0));
    const legacyDays   = Number(nextDays) > 0 ? String(nextDays) : (current.reminder_days_before || '');

    await dbRun(
      `UPDATE credentials SET
        name = COALESCE(?, name), cred_type = COALESCE(?, cred_type), url = COALESCE(?, url),
        username = COALESCE(?, username), cost = COALESCE(?, cost),
        expiry_date = ?, last_changed_date = ?,
        reminder_days_before = ?, notify_email = ?,
        reminder_days = ?, reminder_hours = ?, reminder_minutes = ?
       WHERE id = ?`,
      [name || null, cred_type || null, url ?? null, username ?? null, cost ?? null,
       expiry_date !== undefined ? (expiry_date || null) : current.expiry_date,
       last_changed_date !== undefined ? (last_changed_date || null) : current.last_changed_date,
       legacyDays, nextNotify, nextDays, nextHours, nextMins, req.params.id],
    );

    const updated = await dbGet(`SELECT * FROM credentials WHERE id = ?`, [req.params.id]) as any;
    if (updated?.notify_email && hasReminder && updated.expiry_date) {
      const adminEmails = await resolveMemberNotificationEmails('Admin');
      scheduleCustomReminders({
        entityType: 'credential', entityId: Number(req.params.id),
        targetDateTime: `${updated.expiry_date}T09:00:00+06:00`,
        recipientEmails: adminEmails, title: `Credential Expiry: ${updated.name}`,
        rows: [
          { label: 'Activity', value: updated.name }, { label: 'User', value: updated.username || '—' },
          { label: 'Expiry Date', value: updated.expiry_date }, { label: 'URL', value: updated.url || '—' },
        ],
        reminderDays: updated.reminder_days, reminderHours: updated.reminder_hours, reminderMinutes: updated.reminder_minutes,
      }).catch(console.error);
    } else {
      dbRun(`DELETE FROM email_jobs WHERE entity_type = ? AND entity_id = ? AND status = ?`, ['credential', req.params.id, 'PENDING']).catch(() => {});
    }

    res.json(updated);
  });

  app.delete('/api/credentials/:id', requireRole('Admin'), async (req, res) => {
    await dbRun(`DELETE FROM credentials WHERE id = ?`, [req.params.id]);
    res.json({ ok: true });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── MEETINGS ──────────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  app.get('/api/meetings', requireRole('Admin'), async (_req, res) => {
    res.json(await dbAll(`SELECT * FROM meetings ORDER BY scheduled_at ASC`));
  });

  app.post('/api/meetings', requireRole('Admin'), async (req, res) => {
    const { title, contact_name, scheduled_at, notify_email, reminder_days, reminder_hours, reminder_minutes } = req.body;
    if (!title || !scheduled_at) return res.status(400).json({ error: 'title and scheduled_at are required.' });

    const remDays  = reminder_days    != null && reminder_days    !== '' ? Number(reminder_days)    : null;
    const remHours = reminder_hours   != null && reminder_hours   !== '' ? Number(reminder_hours)   : null;
    const remMins  = reminder_minutes != null && reminder_minutes !== '' ? Number(reminder_minutes) : null;
    const hasReminder  = (remDays && remDays > 0) || (remHours && remHours > 0) || (remMins && remMins > 0);
    const shouldNotify = notify_email ? 1 : (hasReminder ? 1 : 0);
    const legacyMins   = remMins && remMins > 0 ? String(remMins) : '';

    const { lastID } = await dbRun(
      `INSERT INTO meetings(title, contact_name, scheduled_at, reminder_minutes_before, notify_email, reminder_days, reminder_hours, reminder_minutes)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      [title, contact_name || '', scheduled_at, legacyMins, shouldNotify, remDays, remHours, remMins],
    );

    if (shouldNotify && hasReminder) {
      const emails = await resolveMemberNotificationEmails('Admin');
      scheduleCustomReminders({
        entityType: 'meeting', entityId: lastID, targetDateTime: scheduled_at,
        recipientEmails: emails, title: `Meeting: ${title}`,
        rows: [
          { label: 'Meeting',      value: title },
          { label: 'With',         value: contact_name || '—' },
          { label: 'Scheduled At', value: new Date(scheduled_at).toLocaleString('en-GB') },
        ],
        reminderDays: remDays, reminderHours: remHours, reminderMinutes: remMins,
      }).catch(console.error);
      await notifyReminderConfigured({ entityLabel: 'Meeting', title, link: '/meetings', remDays, remHours, remMins });
    }

    res.status(201).json(await dbGet(`SELECT * FROM meetings WHERE id = ?`, [lastID]));
  });

  app.patch('/api/meetings/:id', requireRole('Admin'), async (req, res) => {
    const { title, contact_name, scheduled_at, notify_email, reminder_days, reminder_hours, reminder_minutes } = req.body;
    const current = await dbGet(`SELECT * FROM meetings WHERE id = ?`, [req.params.id]) as any;
    if (!current) return res.status(404).json({ error: 'Meeting not found.' });

    const nextDays  = reminder_days    !== undefined ? (reminder_days    === '' || reminder_days    === null ? null : Number(reminder_days))    : (current.reminder_days    ?? null);
    const nextHours = reminder_hours   !== undefined ? (reminder_hours   === '' || reminder_hours   === null ? null : Number(reminder_hours))   : (current.reminder_hours   ?? null);
    const nextMins  = reminder_minutes !== undefined ? (reminder_minutes === '' || reminder_minutes === null ? null : Number(reminder_minutes)) : (current.reminder_minutes ?? null);
    const hasReminder  = (Number(nextDays) > 0) || (Number(nextHours) > 0) || (Number(nextMins) > 0);
    const nextNotify   = notify_email !== undefined ? (notify_email ? 1 : 0) : (hasReminder ? 1 : (current.notify_email || 0));
    const legacyMins   = Number(nextMins) > 0 ? String(nextMins) : (current.reminder_minutes_before || '');

    await dbRun(
      `UPDATE meetings SET
        title = COALESCE(?, title), contact_name = COALESCE(?, contact_name), scheduled_at = COALESCE(?, scheduled_at),
        reminder_minutes_before = ?, notify_email = ?,
        reminder_days = ?, reminder_hours = ?, reminder_minutes = ?
       WHERE id = ?`,
      [title || null, contact_name ?? null, scheduled_at || null, legacyMins, nextNotify, nextDays, nextHours, nextMins, req.params.id],
    );

    const updated = await dbGet(`SELECT * FROM meetings WHERE id = ?`, [req.params.id]) as any;
    if (updated?.notify_email && hasReminder && updated.scheduled_at) {
      const emails = await resolveMemberNotificationEmails('Admin');
      scheduleCustomReminders({
        entityType: 'meeting', entityId: Number(req.params.id), targetDateTime: updated.scheduled_at,
        recipientEmails: emails, title: `Meeting: ${updated.title}`,
        rows: [
          { label: 'Meeting', value: updated.title },
          { label: 'With',    value: updated.contact_name || '—' },
          { label: 'Scheduled At', value: new Date(updated.scheduled_at).toLocaleString('en-GB') },
        ],
        reminderDays: updated.reminder_days, reminderHours: updated.reminder_hours, reminderMinutes: updated.reminder_minutes,
      }).catch(console.error);
    } else {
      dbRun(`DELETE FROM email_jobs WHERE entity_type = ? AND entity_id = ? AND status = ?`, ['meeting', req.params.id, 'PENDING']).catch(() => {});
    }

    res.json(updated);
  });

  app.delete('/api/meetings/:id', requireRole('Admin'), async (req, res) => {
    await dbRun(`DELETE FROM meetings WHERE id = ?`, [req.params.id]);
    res.json({ ok: true });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── TENDERS ───────────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  app.get('/api/tenders', requireRole('Admin'), async (_req, res) => {
    res.json(await dbAll(`SELECT * FROM tenders ORDER BY submission_deadline ASC`));
  });

  app.post('/api/tenders', requireRole('Admin'), async (req, res) => {
    const { title, organization, tender_type, published_date, submission_deadline, estimated_value, status, documents_url, notes, assigned_to, notify_email, reminder_days, reminder_hours, reminder_minutes } = req.body;
    if (!title || !submission_deadline) return res.status(400).json({ error: 'title and submission_deadline are required.' });

    const remDays  = reminder_days    != null && reminder_days    !== '' ? Number(reminder_days)    : null;
    const remHours = reminder_hours   != null && reminder_hours   !== '' ? Number(reminder_hours)   : null;
    const remMins  = reminder_minutes != null && reminder_minutes !== '' ? Number(reminder_minutes) : null;
    const hasReminder  = (remDays && remDays > 0) || (remHours && remHours > 0) || (remMins && remMins > 0);
    const shouldNotify = notify_email ? 1 : (hasReminder ? 1 : 0);

    const { lastID } = await dbRun(
      `INSERT INTO tenders(title, organization, tender_type, published_date, submission_deadline, estimated_value, status, documents_url, notes, assigned_to, notify_email, reminder_days, reminder_hours, reminder_minutes)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [title, organization || '', tender_type || 'PRIVATE', published_date || null, submission_deadline, estimated_value || 0, status || 'UPCOMING', documents_url || '', notes || '', assigned_to || null, shouldNotify, remDays, remHours, remMins],
    );

    if (shouldNotify && hasReminder) {
      const emails = await resolveMemberNotificationEmails(assigned_to || 'Admin');
      const closingDateTime = submission_deadline.includes('T') ? submission_deadline : `${submission_deadline}T17:00:00+06:00`;
      scheduleTenderReminders({
        entityId: lastID, closingDateTime, recipientEmails: emails, title: `Tender Closing: ${title}`,
        rows: [
          { label: 'Tender',       value: title },
          { label: 'Organization', value: organization || '—' },
          { label: 'Closing Date', value: submission_deadline },
        ],
        reminderDays: remDays, reminderHours: remHours, reminderMinutes: remMins,
      }).catch(console.error);
      await notifyReminderConfigured({ entityLabel: 'Tender', title, link: '/tenders', remDays, remHours, remMins });
    }

    res.status(201).json(await dbGet(`SELECT * FROM tenders WHERE id = ?`, [lastID]));
  });

  app.patch('/api/tenders/:id/status', requireRole('Admin'), async (req, res) => {
    const { status } = req.body;
    await dbRun(`UPDATE tenders SET status = ? WHERE id = ?`, [status, req.params.id]);
    res.json(await dbGet(`SELECT * FROM tenders WHERE id = ?`, [req.params.id]));
  });

  app.patch('/api/tenders/:id', requireRole('Admin'), async (req, res) => {
    const { title, organization, tender_type, published_date, submission_deadline, estimated_value, documents_url, notes, notify_email, reminder_days, reminder_hours, reminder_minutes, status } = req.body;
    const current = await dbGet(`SELECT * FROM tenders WHERE id = ?`, [req.params.id]) as any;
    if (!current) return res.status(404).json({ error: 'Tender not found.' });

    const nextDays  = reminder_days    !== undefined ? (reminder_days    === '' || reminder_days    === null ? null : Number(reminder_days))    : (current.reminder_days    ?? null);
    const nextHours = reminder_hours   !== undefined ? (reminder_hours   === '' || reminder_hours   === null ? null : Number(reminder_hours))   : (current.reminder_hours   ?? null);
    const nextMins  = reminder_minutes !== undefined ? (reminder_minutes === '' || reminder_minutes === null ? null : Number(reminder_minutes)) : (current.reminder_minutes ?? null);
    const hasReminder  = (Number(nextDays) > 0) || (Number(nextHours) > 0) || (Number(nextMins) > 0);
    const nextNotify   = notify_email !== undefined ? (notify_email ? 1 : 0) : (hasReminder ? 1 : (current.notify_email || 0));

    await dbRun(
      `UPDATE tenders SET
        title = COALESCE(?, title), organization = COALESCE(?, organization), tender_type = COALESCE(?, tender_type),
        published_date = ?, submission_deadline = COALESCE(?, submission_deadline),
        estimated_value = COALESCE(?, estimated_value), documents_url = COALESCE(?, documents_url),
        notes = COALESCE(?, notes), notify_email = ?, status = COALESCE(?, status),
        reminder_days = ?, reminder_hours = ?, reminder_minutes = ?
       WHERE id = ?`,
      [title || null, organization || null, tender_type || null,
       published_date !== undefined ? (published_date || null) : current.published_date,
       submission_deadline || null, estimated_value ?? null, documents_url || null, notes || null,
       nextNotify, status || null, nextDays, nextHours, nextMins, req.params.id],
    );

    const updatedTender = await dbGet(`SELECT * FROM tenders WHERE id = ?`, [req.params.id]) as any;
    if (updatedTender?.notify_email && hasReminder && updatedTender.submission_deadline) {
      const emails = await resolveMemberNotificationEmails(updatedTender.assigned_to || 'Admin');
      const closingDateTime = updatedTender.submission_deadline.includes('T') ? updatedTender.submission_deadline : `${updatedTender.submission_deadline}T17:00:00+06:00`;
      scheduleTenderReminders({
        entityId: Number(req.params.id), closingDateTime, recipientEmails: emails, title: `Tender Closing: ${updatedTender.title}`,
        rows: [
          { label: 'Tender',       value: updatedTender.title },
          { label: 'Organization', value: updatedTender.organization || '—' },
          { label: 'Closing Date', value: updatedTender.submission_deadline },
        ],
        reminderDays: updatedTender.reminder_days, reminderHours: updatedTender.reminder_hours, reminderMinutes: updatedTender.reminder_minutes,
      }).catch(console.error);
    } else {
      dbRun(`DELETE FROM email_jobs WHERE entity_type = ? AND entity_id = ? AND status = ?`, ['tender', req.params.id, 'PENDING']).catch(() => {});
    }

    res.json(updatedTender);
  });

  app.delete('/api/tenders/:id', requireRole('Admin'), async (req, res) => {
    await dbRun(`DELETE FROM tenders WHERE id = ?`, [req.params.id]);
    res.json({ ok: true });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── AUTOMATIONS ───────────────────────────────────────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  app.get('/api/automations', requireRole('Admin'), async (_req, res) => {
    res.json(await dbAll(`SELECT * FROM automations ORDER BY created_at DESC`));
  });

  app.post('/api/automations', requireRole('Admin'), async (req, res) => {
    const { name, trigger, action, enabled } = req.body;
    if (!name || !trigger || !action) return res.status(400).json({ error: 'name, trigger, and action are required.' });
    const { lastID } = await dbRun(
      `INSERT INTO automations(name, trigger, action, enabled) VALUES (?, ?, ?, ?)`,
      [name, trigger, action, enabled !== undefined ? (enabled ? 1 : 0) : 1],
    );
    res.status(201).json(await dbGet(`SELECT * FROM automations WHERE id = ?`, [lastID]));
  });

  app.patch('/api/automations/:id', requireRole('Admin'), async (req, res) => {
    const { name, trigger, action, enabled } = req.body;
    const parts: string[] = []; const values: any[] = [];
    if (name    !== undefined) { parts.push('name = ?');    values.push(name); }
    if (trigger !== undefined) { parts.push('trigger = ?'); values.push(trigger); }
    if (action  !== undefined) { parts.push('action = ?');  values.push(action); }
    if (enabled !== undefined) { parts.push('enabled = ?'); values.push(enabled ? 1 : 0); }
    if (parts.length === 0) return res.status(400).json({ error: 'No fields to update.' });
    values.push(req.params.id);
    await dbRun(`UPDATE automations SET ${parts.join(', ')} WHERE id = ?`, values);
    res.json(await dbGet(`SELECT * FROM automations WHERE id = ?`, [req.params.id]));
  });

  app.delete('/api/automations/:id', requireRole('Admin'), async (req, res) => {
    await dbRun(`DELETE FROM automations WHERE id = ?`, [req.params.id]);
    res.json({ ok: true });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // ── REMINDER CRON ENGINE (runs every 60 seconds) ──────────────────────────
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Evaluates all pending reminder conditions and fires in-app + email notifications.
   * Runs once on startup then repeats every 60 seconds.
   *
   * Covers: Credentials, Meetings, Tenders, Tasks, Leaves, Wi-Fi Auto-Checkout,
   *         and Brevo scheduled email job processing.
   */
  const runReminderCron = async () => {
    const now      = new Date();
    const todayStr = now.toISOString().split('T')[0]!;
    const today    = new Date(todayStr);

    // ── Credentials ──────────────────────────────────────────────────────────
    try {
      const creds = await dbAll(`SELECT * FROM credentials`) as any[];
      for (const c of creds) {
        if (!c.expiry_date || !c.notify_email) continue;
        const exp = new Date(`${c.expiry_date}T09:00:00+06:00`);
        if (isNaN(exp.getTime())) continue;

        const diffMs      = exp.getTime() - now.getTime();
        const diffDays    = Math.round(diffMs / (1000 * 60 * 60 * 24));
        const diffMinutes = Math.round(diffMs / (1000 * 60));

        const dayRem = Number(c.reminder_days);
        const hrRem  = Number(c.reminder_hours);
        const minRem = Number(c.reminder_minutes);

        if (Number.isFinite(dayRem) && dayRem > 0 && diffDays === dayRem && now.getMinutes() === 0) {
          await notifyAdmins(`Credential Reminder: "${c.name}" expires in ${dayRem} day(s).`, '/credentials');
        }
        if (Number.isFinite(hrRem) && hrRem > 0 && diffMinutes === hrRem * 60) {
          await notifyAdmins(`Credential Reminder: "${c.name}" expires in ${hrRem} hour(s).`, '/credentials');
        }
        if (Number.isFinite(minRem) && minRem > 0 && diffMinutes === minRem) {
          await notifyAdmins(`Credential Reminder: "${c.name}" expires in ${minRem} minute(s).`, '/credentials');
        }

        // Legacy comma-separated days fallback
        if ((!Number.isFinite(dayRem) || dayRem <= 0) && c.reminder_days_before) {
          const daysArr = String(c.reminder_days_before).split(',').map((d: string) => parseInt(d.trim(), 10)).filter(Number.isFinite);
          const calDiff = Math.ceil((exp.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
          if (daysArr.includes(calDiff) && now.getMinutes() === 0) {
            await notifyAdmins(`Credential Reminder: "${c.name}" expires in ${calDiff} day(s).`, '/credentials');
          }
        }
      }
    } catch (e) { console.error('[Cron] Credentials reminder error:', e); }

    // ── Meetings ─────────────────────────────────────────────────────────────
    try {
      const meetings = await dbAll(`SELECT * FROM meetings`) as any[];
      for (const m of meetings) {
        if (!m.scheduled_at || !m.notify_email) continue;
        let schedStr = String(m.scheduled_at).trim();
        if (!schedStr.includes('Z') && !/[+-]\d{2}(:?\d{2})?$/.test(schedStr)) {
          schedStr = schedStr.replace(' ', 'T') + '+06:00';
        }
        const scheduledTime = new Date(schedStr);
        if (isNaN(scheduledTime.getTime())) continue;

        const diffMs      = scheduledTime.getTime() - now.getTime();
        const diffDays    = Math.round(diffMs / (1000 * 60 * 60 * 24));
        const diffMinutes = Math.round(diffMs / (1000 * 60));

        const dayRem = Number(m.reminder_days);
        const hrRem  = Number(m.reminder_hours);
        const minRem = Number(m.reminder_minutes);

        if (Number.isFinite(dayRem) && dayRem > 0 && diffDays === dayRem && now.getMinutes() === 0) {
          await notifyAdmins(`Meeting Reminder: "${m.title}" in ${dayRem} day(s).`, '/meetings');
        }
        if (Number.isFinite(hrRem) && hrRem > 0 && diffMinutes === hrRem * 60) {
          await notifyAdmins(`Meeting Reminder: "${m.title}" in ${hrRem} hour(s).`, '/meetings');
        }
        if (Number.isFinite(minRem) && minRem > 0 && diffMinutes === minRem) {
          await notifyAdmins(`Meeting Reminder: "${m.title}" in ${minRem} minute(s).`, '/meetings');
        }

        // Legacy comma-separated minutes fallback
        if ((!Number.isFinite(minRem) || minRem <= 0) && m.reminder_minutes_before) {
          const minsArr = String(m.reminder_minutes_before).split(',').map((s: string) => parseInt(s.trim(), 10)).filter((n: number) => Number.isFinite(n) && n > 0);
          if (minsArr.includes(diffMinutes)) {
            await notifyAdmins(`Meeting Reminder: "${m.title}" in ${diffMinutes} minute(s).`, '/meetings');
          }
        }
      }
    } catch (e) { console.error('[Cron] Meetings reminder error:', e); }

    // ── Tenders ───────────────────────────────────────────────────────────────
    try {
      const tenders = await dbAll(`SELECT * FROM tenders`) as any[];
      for (const t of tenders) {
        if (!t.submission_deadline || ['SUBMITTED', 'WON', 'LOST'].includes(t.status)) continue;
        if (!t.notify_email) continue;

        let dlStr = String(t.submission_deadline).trim();
        if (!dlStr.includes('Z') && !/[+-]\d{2}(:?\d{2})?$/.test(dlStr)) dlStr = dlStr.replace(' ', 'T') + '+06:00';
        const deadline = new Date(dlStr);
        if (isNaN(deadline.getTime())) continue;

        const diffMs      = deadline.getTime() - now.getTime();
        const diffDays    = Math.round(diffMs / (1000 * 60 * 60 * 24));
        const diffMinutes = Math.round(diffMs / (1000 * 60));

        const dayRem = Number(t.reminder_days);
        const hrRem  = Number(t.reminder_hours);
        const minRem = Number(t.reminder_minutes);

        if (Number.isFinite(dayRem) && dayRem > 0 && diffDays === dayRem && now.getMinutes() === 0) {
          await notifyAdmins(`Tender Reminder: "${t.title}" closes in ${dayRem} day(s).`, '/tenders');
        }
        if (Number.isFinite(hrRem) && hrRem > 0 && diffMinutes === hrRem * 60) {
          await notifyAdmins(`Tender Reminder: "${t.title}" closes in ${hrRem} hour(s).`, '/tenders');
        }
        if (Number.isFinite(minRem) && minRem > 0 && diffMinutes === minRem) {
          await notifyAdmins(`Tender Reminder: "${t.title}" closes in ${minRem} minute(s).`, '/tenders');
        }
      }
    } catch (e) { console.error('[Cron] Tenders reminder error:', e); }

    // ── Tasks ────────────────────────────────────────────────────────────────
    try {
      const reminderTasks = await dbAll(
        `SELECT * FROM tasks WHERE status != 'DONE' AND deadline IS NOT NULL AND notify_email = 1`,
      ) as any[];
      for (const t of reminderTasks) {
        let dlStr = String(t.deadline).trim();
        if (!dlStr.includes('Z') && !/[+-]\d{2}(:?\d{2})?$/.test(dlStr)) dlStr = dlStr.replace(' ', 'T') + '+06:00';
        const deadline = new Date(dlStr);
        if (isNaN(deadline.getTime())) continue;

        const diffMs      = deadline.getTime() - now.getTime();
        const diffDays    = Math.round(diffMs / (1000 * 60 * 60 * 24));
        const diffMinutes = Math.round(diffMs / (1000 * 60));

        const dayRem = Number(t.reminder_days);
        const hrRem  = Number(t.reminder_hours);
        const minRem = Number(t.reminder_minutes);

        if (Number.isFinite(dayRem) && dayRem > 0 && diffDays === dayRem && now.getMinutes() === 0) {
          await notifyAdmins(`Task Reminder: "${t.title}" due in ${dayRem} day(s).`, '/dashboard');
        }
        if (Number.isFinite(hrRem) && hrRem > 0 && diffMinutes === hrRem * 60) {
          await notifyAdmins(`Task Reminder: "${t.title}" due in ${hrRem} hour(s).`, '/dashboard');
        }
        if (Number.isFinite(minRem) && minRem > 0 && diffMinutes === minRem) {
          await notifyAdmins(`Task Reminder: "${t.title}" due in ${minRem} minute(s).`, '/dashboard');
        }

        // 30-minute in-app reminder for individual assignee (REMINDER action type)
        if (t.action_type === 'REMINDER' && t.assigned_to) {
          const taskDiffMins = Math.round((deadline.getTime() - now.getTime()) / (1000 * 60));
          if (taskDiffMins <= 30 && taskDiffMins >= 0) {
            const existingNotif = await dbGet(
              `SELECT id FROM notifications WHERE member_id = ? AND message LIKE ?`,
              [t.assigned_to, `%The task "${t.title}"%`],
            );
            if (!existingNotif) {
              const timeLabel = taskDiffMins <= 1 ? 'less than a minute' : `${taskDiffMins} minutes`;
              await notifyMember(t.assigned_to, `Reminder: The task "${t.title}" is due in ${timeLabel}!`, '/dashboard');
            }
          }
        }
      }
    } catch (e) { console.error('[Cron] Tasks reminder error:', e); }

    // ── Leaves ───────────────────────────────────────────────────────────────
    try {
      const leaveRows = await dbAll(
        `SELECT l.*, m.name AS member_name
         FROM leave_requests l LEFT JOIN members m ON l.member_id = m.id
         WHERE l.notify_email = 1 AND l.status NOT IN ('REJECTED', 'CANCELLED')`,
      ) as any[];
      for (const l of leaveRows) {
        if (!l.start_date) continue;
        let dlStr = String(l.start_date).trim();
        if (!dlStr.includes('T')) dlStr = `${dlStr}T09:00:00+06:00`;
        const deadline = new Date(dlStr);
        if (isNaN(deadline.getTime())) continue;

        const diffMs      = deadline.getTime() - now.getTime();
        const diffDays    = Math.round(diffMs / (1000 * 60 * 60 * 24));
        const diffMinutes = Math.round(diffMs / (1000 * 60));

        const dayRem = Number(l.reminder_days);
        const hrRem  = Number(l.reminder_hours);
        const minRem = Number(l.reminder_minutes);
        const who    = l.member_name || 'Employee';

        if (Number.isFinite(dayRem) && dayRem > 0 && diffDays === dayRem && now.getMinutes() === 0) {
          await notifyAdmins(`Leave Reminder: ${who} (${l.leave_type}) starts in ${dayRem} day(s).`, '/hr?tab=leave');
        }
        if (Number.isFinite(hrRem) && hrRem > 0 && diffMinutes === hrRem * 60) {
          await notifyAdmins(`Leave Reminder: ${who} (${l.leave_type}) starts in ${hrRem} hour(s).`, '/hr?tab=leave');
        }
        if (Number.isFinite(minRem) && minRem > 0 && diffMinutes === minRem) {
          await notifyAdmins(`Leave Reminder: ${who} (${l.leave_type}) starts in ${minRem} minute(s).`, '/hr?tab=leave');
        }
      }
    } catch (e) { console.error('[Cron] Leaves reminder error:', e); }

    // ── Wi-Fi Auto Checkout ───────────────────────────────────────────────────
    try {
      const timeoutRow  = await dbGet(`SELECT value FROM settings WHERE key = 'auto_checkout_timeout_minutes'`) as any;
      const enabledRow  = await dbGet(`SELECT value FROM settings WHERE key = 'wifi_auto_attendance_enabled'`) as any;
      const isEnabled   = enabledRow?.value !== 'false';
      const timeoutMins = parseInt(timeoutRow?.value || '10', 10);

      if (isEnabled) {
        const cutoffIso      = new Date(Date.now() - timeoutMins * 60 * 1000).toISOString();
        const expiredSessions = await dbAll(
          `SELECT a.member_id, a.last_seen, m.name FROM active_sessions a JOIN members m ON a.member_id = m.id WHERE a.is_wifi = 1 AND a.last_seen < ?`,
          [cutoffIso],
        ) as any[];

        for (const s of expiredSessions) {
          const todayDhaka = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' });
          const hasIn  = await dbGet(`SELECT id FROM attendance WHERE member_id = ? AND date(timestamp) = ? AND action_type = 'IN'`,  [s.member_id, todayDhaka]);
          const hasOut = await dbGet(`SELECT id FROM attendance WHERE member_id = ? AND date(timestamp) = ? AND action_type = 'OUT'`, [s.member_id, todayDhaka]);
          if (hasIn && !hasOut) {
            await dbRun(`INSERT INTO attendance(member_id, action_type, timestamp) VALUES (?, 'OUT', ?)`, [s.member_id, new Date().toISOString()]);
            console.log(`[Cron] Auto check-out: ${s.name} (${timeoutMins}m Wi-Fi timeout).`);
          }
          await dbRun(`DELETE FROM active_sessions WHERE member_id = ?`, [s.member_id]);
        }
      }
    } catch (e) { console.error('[Cron] Wi-Fi auto-checkout error:', e); }

    // ── Scheduled Email Jobs (Brevo) ──────────────────────────────────────────
    try {
      await processDueEmailJobs();
    } catch (e) { console.error('[Cron] Brevo email jobs error:', e); }
  };

  // Kick off the cron immediately then run every 60 seconds
  runReminderCron();
  setInterval(runReminderCron, 60 * 1000);

  return app;
}
